In [201]:
import pandas as pd
import numpy as np
import openpyxl

In [202]:
# ============== Caminho do arquivo Captação
caminhoauc = r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Projetos Power Bi\Relatórios\Evolucao_PL.xlsx"

# ============== Criando DF para trabalhar com os dados Captação
auc = pd.read_excel(caminhoauc)

In [203]:
auc.head()

,Data,Conta,Nome,Mercado,Sub Mercado,Produto,CNPJ,Emissor,Ativo,Vencimento,Quantidade,Valor Bruto,IR,IOF,Valor Líquido,Estratégia,Escritório,ID
0,2022-01-01,3475,ANA,Conta Corrente,CC,Conta Corrente,NaN,NaN,NaN,NaN,4943.84,4943.84,NaN,NaN,4943.84,NaN,OMEGA INVEST ASSESSORIA DE INVESTIMENTOS LTDA.,18686568
1,2022-01-01,3475,ANA,Renda Fixa,RF,CDB,NaN,BANCO BTG PACTUAL S A,CDB-CDB321D7B80,2023-08-18 00:00:00,5770826.00,59643.16,435.35,0.0,59207.81,Pós-fixado,OMEGA INVEST ASSESSORIA DE INVESTIMENTOS LTDA.,3263779
2,2022-01-01,3475,ANA,Renda Variável,ACAO,GGBR4,NaN,NaN,GGBR4,NaN,7117.00,198137.28,0.00,NaN,198137.28,Renda Variável,OMEGA INVEST ASSESSORIA DE INVESTIMENTOS LTDA.,19174164
3,2022-01-01,3475,ANA,Valor em Trânsito,RV,COMPRA - GGBR4,NaN,NaN,NaN,2022-02-01 00:00:00,1.00,-201342.34,NaN,NaN,-201342.34,NaN,OMEGA INVEST ASSESSORIA DE INVESTIMENTOS LTDA.,567047
4,2022-01-01,3475,ANA,Valor em Trânsito,RV,JUROS S/ CAPITAL - BRADESCO PN N1,NaN,NaN,NaN,2022-02-01 00:00:00,1.00,14.61,NaN,NaN,14.61,NaN,OMEGA INVEST ASSESSORIA DE INVESTIMENTOS LTDA.,567049

In [204]:
auc = auc[['Data','Conta','Valor Bruto']]

In [205]:
auc['Ano'] = auc['Data'].dt.strftime('%Y')
auc['MesNum'] = auc['Data'].dt.strftime('%m')
auc['Mês/Ano'] = auc['Ano'] + "-" + auc['MesNum']

In [206]:
auc['NomeMês'] = auc['Data'].dt.strftime('%B')

In [207]:
auc

             Data    Conta  Valor Bruto   Ano MesNum  Mês/Ano  NomeMês
0      2022-01-01     3475      4943.84  2022     01  2022-01  January
1      2022-01-01     3475     59643.16  2022     01  2022-01  January
2      2022-01-01     3475    198137.28  2022     01  2022-01  January
3      2022-01-01     3475   -201342.34  2022     01  2022-01  January
4      2022-01-01     3475        14.61  2022     01  2022-01  January
...           ...      ...          ...   ...    ...      ...      ...
174278 2024-06-01  4269461     73210.61  2024     06  2024-06     June
174279 2024-06-01  1439204    100246.89  2024     06  2024-06     June
174280 2024-06-01  3970409    123334.05  2024     06  2024-06     June
174281 2024-06-01  4253178       688.82  2024     06  2024-06     June
174282 2024-06-01  4253178    100633.50  2024     06  2024-06     June

[174283 rows x 7 columns]

In [208]:
Ultimo_Mes = auc['Mês/Ano'].max()

In [209]:
auc_ultimo_mes = auc[auc['Mês/Ano'] == '2023-11']

In [210]:
auc_ultimo_mes

             Data    Conta  Valor Bruto   Ano MesNum  Mês/Ano   NomeMês
111802 2023-11-01     3475         0.00  2023     11  2023-11  November
111803 2023-11-01     3475     62261.60  2023     11  2023-11  November
111804 2023-11-01   108375         0.00  2023     11  2023-11  November
111805 2023-11-01   108375     61568.97  2023     11  2023-11  November
111806 2023-11-01   108375     72318.76  2023     11  2023-11  November
...           ...      ...          ...   ...    ...      ...       ...
119188 2023-11-01  5976667    124037.55  2023     11  2023-11  November
119189 2023-11-01  5976667    143825.50  2023     11  2023-11  November
119190 2023-11-01  5976667     44366.08  2023     11  2023-11  November
119191 2023-11-01  5976667      1677.90  2023     11  2023-11  November
119192 2023-11-01  5976667        59.67  2023     11  2023-11  November

[7391 rows x 7 columns]

In [211]:
auc_actual = auc_ultimo_mes['Valor Bruto'].sum()
auc_actual

965426115.762901

In [212]:
auc

             Data    Conta  Valor Bruto   Ano MesNum  Mês/Ano  NomeMês
0      2022-01-01     3475      4943.84  2022     01  2022-01  January
1      2022-01-01     3475     59643.16  2022     01  2022-01  January
2      2022-01-01     3475    198137.28  2022     01  2022-01  January
3      2022-01-01     3475   -201342.34  2022     01  2022-01  January
4      2022-01-01     3475        14.61  2022     01  2022-01  January
...           ...      ...          ...   ...    ...      ...      ...
174278 2024-06-01  4269461     73210.61  2024     06  2024-06     June
174279 2024-06-01  1439204    100246.89  2024     06  2024-06     June
174280 2024-06-01  3970409    123334.05  2024     06  2024-06     June
174281 2024-06-01  4253178       688.82  2024     06  2024-06     June
174282 2024-06-01  4253178    100633.50  2024     06  2024-06     June

[174283 rows x 7 columns]

In [213]:
auc = auc.groupby(['Mês/Ano','Ano','NomeMês','Conta'])['Valor Bruto'].sum().reset_index()

In [214]:
auc

       Mês/Ano   Ano  NomeMês    Conta  Valor Bruto
0      2022-01  2022  January     3475    376723.11
1      2022-01  2022  January   108375    256158.33
2      2022-01  2022  January   142638     22187.00
3      2022-01  2022  January   305582    268681.13
4      2022-01  2022  January   365708        22.83
...        ...   ...      ...      ...          ...
18811  2024-06  2024     June  5879093     11308.81
18812  2024-06  2024     June  5879473    281440.04
18813  2024-06  2024     June  5930490    965984.40
18814  2024-06  2024     June  5964283     86992.31
18815  2024-06  2024     June  5976667    643144.14

[18816 rows x 5 columns]

In [215]:
auc['Valor Bruto'] = auc['Valor Bruto'].round(2)

In [216]:
auc_ultimo_mes = auc[auc['Mês/Ano'] == '2023-11']
auc_ultimo_mes = auc_ultimo_mes['Valor Bruto'].sum()

In [217]:
auc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18816 entries, 0 to 18815
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mês/Ano      18816 non-null  object
 1   Ano          18816 non-null  object
 2   NomeMês      18816 non-null  object
 3   Conta        18816 non-null  int64
 4   Valor Bruto  18816 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 735.1+ KB

## CAPTAÇÃO

In [218]:
# ============== Caminho do arquivo Captação
captacao = r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Projetos Power Bi\Relatórios\CaptacaoGeral.xlsx"

# ============== Criando DF para trabalhar com os dados Captação
dfcapt = pd.read_excel(captacao)

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning:

Unknown extension is not supported and will be removed

In [219]:
dfcapt = dfcapt.rename(columns={'DATAOFICIAL':'Data'})

In [220]:
dfcapt['Ano'] = dfcapt['Data'].dt.strftime('%Y')
dfcapt['MesNum'] = dfcapt['Data'].dt.strftime('%m')
dfcapt['MesNome'] = dfcapt['Data'].dt.strftime('%b')
dfcapt['MesNumero'] = dfcapt['Data'].dt.month

dfcapt['DataBr'] = dfcapt['Data'].dt.strftime('%d/%m/%Y')

dfcapt['AnoMes'] = dfcapt['Ano'] + "-" + dfcapt['MesNum']

In [221]:
dfcapt = dfcapt.dropna(subset=['CAPTAÇÃO'])

In [222]:
dfcapt['Ano'] = dfcapt['Data'].dt.strftime('%Y')
dfcapt['MesNum'] = dfcapt['Data'].dt.strftime('%m')
dfcapt['Mês/Ano'] = dfcapt['Ano'] + "-" + dfcapt['MesNum']

In [223]:
dfcapt = dfcapt[['Mês/Ano','Conta','CAPTAÇÃO']]

In [224]:
dfcapt = dfcapt.groupby(['Mês/Ano','Conta'])['CAPTAÇÃO'].sum().reset_index()

In [225]:
dfcapt['CAPTAÇÃO'] = dfcapt['CAPTAÇÃO'].round(2)

In [226]:
auc_ultimo_mes = dfcapt[dfcapt['Mês/Ano'] == '2024-06']
auc_ultimo_mes = auc_ultimo_mes['CAPTAÇÃO'].sum()
auc_ultimo_mes

3802767.7800000003

#### Auc e Captação estão sempre contabilizados para o dono do relacionamento. Ou seja, não há divisão entre assessores e isso implita em deixar para o próprio cliente e seu assessor "dono"

### Sendo Assim o AUC e a Captação podem fazer o Merge sem problema

In [227]:
# Mesclar os dataframes 'a' e 'b' com base nas colunas "Mês/Ano" e "Conta"
Auc_Captacao = pd.merge(auc, dfcapt, on=["Mês/Ano", "Conta"], how="left")

In [228]:
Auc_Captacao

       Mês/Ano   Ano  NomeMês    Conta  Valor Bruto  CAPTAÇÃO
0      2022-01  2022  January     3475    376723.11       NaN
1      2022-01  2022  January   108375    256158.33       NaN
2      2022-01  2022  January   142638     22187.00       NaN
3      2022-01  2022  January   305582    268681.13  -8800.01
4      2022-01  2022  January   365708        22.83   1000.00
...        ...   ...      ...      ...          ...       ...
18811  2024-06  2024     June  5879093     11308.81       NaN
18812  2024-06  2024     June  5879473    281440.04       NaN
18813  2024-06  2024     June  5930490    965984.40       NaN
18814  2024-06  2024     June  5964283     86992.31       NaN
18815  2024-06  2024     June  5976667    643144.14       NaN

[18816 rows x 6 columns]

In [229]:
Auc_Captacao['CAPTAÇÃO'] = Auc_Captacao['CAPTAÇÃO'].fillna(0)

In [230]:
Auc_Captacao

       Mês/Ano   Ano  NomeMês    Conta  Valor Bruto  CAPTAÇÃO
0      2022-01  2022  January     3475    376723.11      0.00
1      2022-01  2022  January   108375    256158.33      0.00
2      2022-01  2022  January   142638     22187.00      0.00
3      2022-01  2022  January   305582    268681.13  -8800.01
4      2022-01  2022  January   365708        22.83   1000.00
...        ...   ...      ...      ...          ...       ...
18811  2024-06  2024     June  5879093     11308.81      0.00
18812  2024-06  2024     June  5879473    281440.04      0.00
18813  2024-06  2024     June  5930490    965984.40      0.00
18814  2024-06  2024     June  5964283     86992.31      0.00
18815  2024-06  2024     June  5976667    643144.14      0.00

[18816 rows x 6 columns]

### Trazendo a Base de atendimento

In [231]:
basecaminho = r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Base Atendimentos\Base_OmegaInvest_Ofc.xlsx"
 
base = pd.read_excel(basecaminho)

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning:

Unknown extension is not supported and will be removed

In [232]:
# Remover duplicatas na coluna 'Conta'
base = base.drop_duplicates(subset=['Conta'])

### Merge com Nome e Assessor "dono"

In [233]:
# Mesclar os dataframes 'a' e 'b' com base nas colunas "Mês/Ano" e "Conta"
Auc_Captacao_base = pd.merge(Auc_Captacao, base, on=["Conta"], how="left")

In [234]:
Auc_Captacao_base = Auc_Captacao_base.drop(columns=['Assessor_RV', 'Assessor_RF'])

In [235]:
Auc_Captacao_base = Auc_Captacao_base[['Mês/Ano','Ano','NomeMês','Conta','Nome','Assessor','Valor Bruto','CAPTAÇÃO']]

In [236]:
Auc_Captacao_base

,Mês/Ano,Ano,NomeMês,Conta,Nome,Assessor,Valor Bruto,CAPTAÇÃO
0,2022-01,2022,January,3475,ANA,ROBERTA HELENA PIGNATARI,376723.11,0.00
1,2022-01,2022,January,108375,ROSA,PAULO GOMES PAIVA,256158.33,0.00
2,2022-01,2022,January,142638,MARCO,VIVIANE APARECIDA NEVES BENEDITO,22187.00,0.00
3,2022-01,2022,January,305582,BRUNO,ROBERTA HELENA PIGNATARI,268681.13,-8800.01
4,2022-01,2022,January,365708,PAULO,SAULO DE SOUZA FREITAS,22.83,1000.00
...,...,...,...,...,...,...,...,...
18811,2024-06,2024,June,5879093,LUIS,RONALDO CARVALHO FERNANDES JUNIOR,11308.81,0.00
18812,2024-06,2024,June,5879473,FRANCISCO,VINICIUS AUGUSTO BASILIO,281440.04,0.00
18813,2024-06,2024,June,5930490,ELISEU,RODRIGO SCORSSOLINE MARTINS,965984.40,0.00
18814,2024-06,2024,June,5964283,MARCO,ROBERTA HELENA PIGNATARI,86992.31,0.00
18815,2024-06,2024,June,5976667,FERNANDO,VINICIUS AUGUSTO BASILIO,643144.14,0.00

In [237]:
auc_ultimo_mes = Auc_Captacao_base[Auc_Captacao_base['Mês/Ano'] == '2024-01']
auc_ultimo_mes = auc_ultimo_mes['Valor Bruto'].sum()
auc_ultimo_mes

1289599067.13

In [238]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    'Mês/Ano': ['2023-01', '2023-02', '2023-03'],
    'Conta': [3475, 108375, 142638],
    'Assessor Principal': ['Assessor A', 'Assessor B', 'Assessor C'],
    'Receita Bruta': [1000, 2000, 1500]
})

# DataFrame 2
df2 = pd.DataFrame({
    'Mês/Ano': ['2023-04', '2023-05', '2023-06'],
    'Conta': [305582, 330022, 365708],
    'Assessor Principal': ['Assessor D', 'Assessor E', 'Assessor F'],
    'Comissão': [500, 600, 700]
})

# Concatenar os DataFrames
df_concatenated = pd.concat([df1, df2], ignore_index=True)



print(df_concatenated)

   Mês/Ano   Conta Assessor Principal  Receita Bruta  Comissão
0  2023-01    3475         Assessor A         1000.0       NaN
1  2023-02  108375         Assessor B         2000.0       NaN
2  2023-03  142638         Assessor C         1500.0       NaN
3  2023-04  305582         Assessor D            NaN     500.0
4  2023-05  330022         Assessor E            NaN     600.0
5  2023-06  365708         Assessor F            NaN     700.0

### Para receita é importante verificar que há necessidade de divisão dos comissionamentos.

In [239]:
relatorio_caminho = r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Projetos Power Bi\Relatórios\Fechamento.xlsx"

relatorio = pd.read_excel(relatorio_caminho, sheet_name='Comissões')

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning:

Unknown extension is not supported and will be removed

In [240]:
df = relatorio

In [241]:
import datetime as dt

In [242]:
df['Data Receita'] = pd.to_datetime(df['Data Receita'])
df['Mês/Ano'] = df['Data Receita'].dt.to_period('M')

In [243]:
df.dropna(subset=['Receita Bruta'])

,Data Receita,Conta,Cliente,Assessor Principal,Categoria,Produto,Ativo,Código/CNPJ,Tipo Receita,Receita Bruta,Receita Líquida,Comissão,% Comissão,Assessor Oficial,Assessor,Conferencia,Coluna1,Mês/Ano
0,2021-01-01,5879093,LUIS FERNANDO PANEQUE GARCIA,RONALDO CARVALHO FERNANDES,RENDA VARIÁVEL,COMISSÃO ALUGUEL,COMISSÃO ALUGUEL,BOVA11,JUROS,0.2,0.18,0.13,0.722222,NaN,0,RODRIGO SCORSSOLINE MARTINS,RONALDO CARVALHO FERNANDES,2021-01
1,2021-01-01,4262580,SIDNEI SHIROMA,SAULO DE SOUZA FREITAS,RENDA VARIÁVEL,COMISSÃO ALUGUEL,COMISSÃO ALUGUEL,BOVV11,JUROS,1.2,1.08,0.76,0.703704,NaN,0,SAULO DE SOUZA FREITAS,SAULO DE SOUZA FREITAS,2021-01
2,2021-01-01,4262580,SIDNEI SHIROMA,SAULO DE SOUZA FREITAS,RENDA VARIÁVEL,COMISSÃO ALUGUEL,COMISSÃO ALUGUEL,BOVV11,JUROS,1.2,1.08,0.76,0.703704,NaN,0,SAULO DE SOUZA FREITAS,SAULO DE SOUZA FREITAS,2021-01
3,2021-01-01,4929360,JOSE CARLOS LAMEGAL DA FONSECA,NaN,RENDA VARIÁVEL,COMISSÃO ALUGUEL,COMISSÃO ALUGUEL,VALE3,JUROS,0.3,0.27,0.19,0.703704,NaN,0,Não Consta,NaN,2021-01
4,2021-01-01,4929360,JOSE CARLOS LAMEGAL DA FONSECA,NaN,RENDA VARIÁVEL,COMISSÃO ALUGUEL,COMISSÃO ALUGUEL,VALE3,JUROS,0.3,0.27,0.19,0.703704,NaN,0,Não Consta,NaN,2021-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166392,2024-06-07,4425179,GUILHERME REBUSTINI,WILLIAN MATTOS SATURNINI DE OLIVEIRA,SALDO REMUNERADO,Saldo Remunerado Transacional,Saldo Remunerado Transacional,SALDO REMUNERADO TRANSACIONAL,Accrual,0.001513,0.001513,0.001513,1.000000,NaN,0,WILLIAN MATTOS SATURNINI DE OLIVEIRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,2024-06
166393,2024-06-07,3872957,ROBINSON DOS SANTOS,WILLIAN MATTOS SATURNINI DE OLIVEIRA,SALDO REMUNERADO,Saldo Remunerado Transacional,Saldo Remunerado Transacional,SALDO REMUNERADO TRANSACIONAL,Accrual,0.000553,0.000553,0.000553,1.000000,NaN,0,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,2024-06
166394,2024-06-07,3331554,SAMUEL DAVISON CONRADO DUTRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,SALDO REMUNERADO,Saldo Remunerado Transacional,Saldo Remunerado Transacional,SALDO REMUNERADO TRANSACIONAL,Accrual,0.0,0.0,0.0,1.000000,NaN,0,WILLIAN MATTOS SATURNINI DE OLIVEIRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,2024-06
166395,2024-06-07,3988983,THIAGO PAES BARRETO,WILLIAN MATTOS SATURNINI DE OLIVEIRA,SALDO REMUNERADO,Saldo Remunerado Transacional,Saldo Remunerado Transacional,SALDO REMUNERADO TRANSACIONAL,Accrual,0.014122,0.014122,0.014122,1.000000,NaN,0,WILLIAN MATTOS SATURNINI DE OLIVEIRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,2024-06
166396,2024-06-07,4215713,VIVIANE LIMA DE PAULA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,SALDO REMUNERADO,Saldo Remunerado Transacional,Saldo Remunerado Transacional,SALDO REMUNERADO TRANSACIONAL,Accrual,0.004982,0.004982,0.004982,1.000000,NaN,0,WILLIAN MATTOS SATURNINI DE OLIVEIRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,2024-06

In [244]:
df['Receita Bruta'] = pd.to_numeric(df['Receita Bruta'], errors='coerce')
df['Comissão'] = pd.to_numeric(df['Comissão'], errors='coerce')
df['Receita Líquida'] = pd.to_numeric(df['Receita Líquida'], errors='coerce')

In [245]:
df = df.dropna(subset=['Receita Bruta'])

In [246]:
relatorio = df.groupby(['Mês/Ano', 'Assessor Principal', 'Conta', 'Cliente', 'Categoria']).agg({'Receita Bruta':'sum','Receita Líquida':'sum','Comissão':'sum'}).reset_index()

In [247]:
df_dono = relatorio

In [248]:
df_dono

,Mês/Ano,Assessor Principal,Conta,Cliente,Categoria,Receita Bruta,Receita Líquida,Comissão
0,2021-01,JONAS VICENTE DA SILVA,3712262,SAULO DE SOUZA FREITAS,FUNDOS,0.000000,0.000000,0.000000
1,2021-01,JONAS VICENTE DA SILVA,3712262,SAULO DE SOUZA FREITAS,RENDA FIXA,52.380000,49.940000,24.970000
2,2021-01,JONAS VICENTE DA SILVA,3712262,SAULO DE SOUZA FREITAS,RENDA VARIÁVEL,12.390000,11.200000,7.830000
3,2021-01,JONAS VICENTE DA SILVA,4767091,JONAS VICENTE DA SILVA,RENDA FIXA,1.140000,1.090000,0.540000
4,2021-01,PAULO GOMES PAIVA,4426730,JOSE CARLOS VASCONCELOS,FUNDOS,0.000000,0.000000,1.340000
...,...,...,...,...,...,...,...,...
28421,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,3331554,SAMUEL DAVISON CONRADO DUTRA,SALDO REMUNERADO,0.000002,0.000002,0.000002
28422,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,3872957,ROBINSON DOS SANTOS,SALDO REMUNERADO,0.002962,0.002962,0.002962
28423,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,3988983,THIAGO PAES BARRETO,SALDO REMUNERADO,0.024803,0.024803,0.024803
28424,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,4215713,VIVIANE LIMA DE PAULA,SALDO REMUNERADO,0.053240,0.053240,0.053240
28425,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,4425179,GUILHERME REBUSTINI,SALDO REMUNERADO,0.021860,0.021860,0.021860

In [249]:
 
basecaminho = r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Base Atendimentos\Base_OmegaInvest_Ofc.xlsx"
 
base = pd.read_excel(basecaminho)

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning:

Unknown extension is not supported and will be removed

In [250]:
# Remover duplicatas na coluna 'Conta'
base = base.drop_duplicates(subset=['Conta'])

In [251]:
baseRV = base[['Conta', 'Assessor_RV']]

In [252]:
baseRF = base[['Conta', 'Assessor_RF']]

In [253]:
# Retirando os Não Consta
 
baseRV = baseRV[~baseRV['Assessor_RV'].str.contains("Não Consta", na=False)]
baseRV = baseRV[~baseRV['Assessor_RV'].str.contains("SAULO DE SOUZA FREITAS", na=False)]
baseRV = baseRV[~baseRV['Assessor_RV'].str.contains("JONAS VICENTE DA SILVA", na=False)]
baseRV = baseRV[~baseRV['Assessor_RV'].str.contains("WILLIAN MATTOS SATURNINI DE OLIVEIRA", na=False)]
baseRV = baseRV[~baseRV['Assessor_RV'].str.contains("WELBER MATTOS SATURNINI DE OLIVEIRA", na=False)]

In [254]:
# Retirando os Informar
 
baseRF = baseRF[~baseRF['Assessor_RF'].str.contains("Informar", na=False)]
baseRF = baseRF[~baseRF['Assessor_RF'].str.contains("SAULO DE SOUZA FREITAS", na=False)]
baseRF = baseRF[~baseRF['Assessor_RF'].str.contains("JONAS VICENTE DA SILVA", na=False)]
baseRF = baseRF[~baseRF['Assessor_RF'].str.contains("WILLIAN MATTOS SATURNINI DE OLIVEIRA", na=False)]
baseRF = baseRF[~baseRF['Assessor_RF'].str.contains("WELBER MATTOS SATURNINI DE OLIVEIRA", na=False)]
baseRF = baseRF[~baseRF['Assessor_RF'].str.contains("WELLINGTON DA SILVA COELHO", na=False)]

In [255]:
df_ger = df_dono.copy()

In [256]:
df_ger_rf = df_dono.copy()

In [257]:
categorias_filtradas_rv = ['RENDA VARIAVEL','OPERACOES ESTRUTURADAS']
 
df_filtradorv = df_ger[df_ger['Categoria'].isin(categorias_filtradas_rv)]

In [258]:
categorias_filtradas_rf = ['RENDA FIXA']
 
df_filtradorf = df_ger_rf[df_ger_rf['Categoria'].isin(categorias_filtradas_rf)]

In [259]:
df_filtradorv = df_filtradorv.merge(baseRV[['Conta', 'Assessor_RV']], on='Conta', how='left')

In [260]:
df_filtradorf = df_filtradorf.merge(baseRF[['Conta', 'Assessor_RF']], on='Conta', how='left')

In [261]:
df_filtradorv['Assessor_RV'].fillna(df_filtradorv['Assessor Principal'], inplace=True)

In [262]:
df_filtradorf['Assessor_RF'].fillna(df_filtradorf['Assessor Principal'], inplace=True)

In [263]:
condicao = df_filtradorv["Assessor Principal"] != df_filtradorv["Assessor_RV"]
df_diferentes = df_filtradorv[condicao]

In [264]:
condicao2 = df_filtradorv["Assessor Principal"] == df_filtradorv["Assessor_RV"]
df_igual_rv = df_filtradorv[condicao2]

In [265]:
#Filtrar o DataFrame:
 
condicaoRF = df_filtradorf["Assessor Principal"] != df_filtradorf["Assessor_RF"]
df_diferentesRF = df_filtradorf[condicaoRF]

In [266]:
#Filtrar o DataFrame:
 
condicaoRF2 = df_filtradorf["Assessor Principal"] == df_filtradorf["Assessor_RF"]
df_igual_rf = df_filtradorf[condicaoRF2]

In [267]:
df_diferentes_ger = df_diferentes.copy()

In [268]:
df_diferentes_gerRF = df_diferentesRF.copy()

In [269]:
import numpy as np

# Substitua 'df_diferentes_ger' pelo nome do seu DataFrame, se necessário

# Lista de nomes para verificar na coluna 'Assessor Principal'
nomes = [
    "DIOGO GOMES RAMOS",
    "GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA",
    "JOAO PAULO ALVES SOARES",
    "KAUE DEL DUQUE DE GODOY",
    "LUCIANA FERREIRA GONCALVES ABADE",
    "ALINE DE OLIVEIRA",
    "RODRIGO MOSSIN PANSICA"
]

# Cria a condição verificando se o valor na coluna 'Assessor Principal' está na lista de nomes
condicao = df_diferentes_ger['Assessor Principal'].isin(nomes)

# Aplica a condição usando np.where e calcula os valores com base na condição
df_diferentes_ger['Nova Receita Bruta'] = np.where(condicao, df_diferentes_ger['Receita Bruta'] * 0.50, df_diferentes_ger['Receita Bruta'] * 0.628571)

df_diferentes_ger['Nova Comissão'] = np.where(condicao, df_diferentes_ger['Comissão'] * 0.50, df_diferentes_ger['Comissão'] * 0.628571)

df_diferentes_ger['Nova Receita Líquida'] = np.where(condicao, df_diferentes_ger['Receita Líquida'] * 0.50, df_diferentes_ger['Receita Líquida'] * 0.628571)

In [270]:
df_diferentes_ger['Receita Bruta'] = df_diferentes_ger['Nova Receita Bruta']

df_diferentes_ger['Comissão'] = df_diferentes_ger['Nova Comissão']

df_diferentes_ger['Receita Líquida'] = df_diferentes_ger['Nova Receita Líquida']

In [271]:
import numpy as np

# Substitua 'df_diferentes_ger' pelo nome do seu DataFrame, se necessário

# Lista de nomes para verificar na coluna 'Assessor Principal'
nomes = [
    "DIOGO GOMES RAMOS",
    "GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA",
    "JOAO PAULO ALVES SOARES",
    "KAUE DEL DUQUE DE GODOY",
    "LUCIANA FERREIRA GONCALVES ABADE",
    "ALINE DE OLIVEIRA",
    "RODRIGO MOSSIN PANSICA"
]

# Cria a condição verificando se o valor na coluna 'Assessor Principal' está na lista de nomes
condicao = df_diferentes_gerRF['Assessor Principal'].isin(nomes)

# Aplica a condição usando np.where e calcula os valores com base na condição
df_diferentes_gerRF['Nova Receita Bruta'] = np.where(condicao, df_diferentes_gerRF['Receita Bruta'] * 0.50, df_diferentes_gerRF['Receita Bruta'] * 0.6667)

df_diferentes_gerRF['Nova Receita Líquida'] = np.where(condicao, df_diferentes_gerRF['Receita Líquida'] * 0.50, df_diferentes_gerRF['Receita Líquida'] * 0.6667)

df_diferentes_gerRF['Nova Comissão'] = np.where(condicao, df_diferentes_gerRF['Comissão'] * 0.50, df_diferentes_gerRF['Comissão'] * 0.6667)

In [272]:
df_diferentes_gerRF['Receita Bruta'] = df_diferentes_gerRF['Nova Receita Bruta']

df_diferentes_gerRF['Receita Líquida'] = df_diferentes_gerRF['Nova Receita Líquida']

df_diferentes_gerRF['Comissão'] = df_diferentes_gerRF['Nova Comissão']

In [273]:
df_diferentes31 = df_diferentes.copy()

In [274]:
df_diferentes31RF = df_diferentesRF.copy()

In [275]:

# Lista de nomes para verificar na coluna 'Assessor Principal'
nomes = [
    "DIOGO GOMES RAMOS",
    "GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA",
    "JOAO PAULO ALVES SOARES",
    "KAUE DEL DUQUE DE GODOY",
    "LUCIANA FERREIRA GONCALVES ABADE",
    "ALINE DE OLIVEIRA",
    "RODRIGO MOSSIN PANSICA"
]

# Cria a condição verificando se o valor na coluna 'Assessor Principal' está na lista de nomes
condicao = df_diferentes31['Assessor Principal'].isin(nomes)

# Aplica a condição usando np.where e calcula os valores com base na condição
df_diferentes31['Nova Receita Bruta'] = np.where(condicao, df_diferentes31['Receita Bruta'] * 0.50, df_diferentes31['Receita Bruta'] * 0.371429)

df_diferentes31['Nova Receita Líquida'] = np.where(condicao, df_diferentes31['Receita Líquida'] * 0.50, df_diferentes31['Receita Líquida'] * 0.371429)

df_diferentes31['Nova Comissão'] = np.where(condicao, df_diferentes31['Comissão'] * 0.50, df_diferentes31['Comissão'] * 0.371429)

In [276]:
df_diferentes31['Receita Bruta'] = df_diferentes31['Nova Receita Bruta']

df_diferentes31['Receita Líquida'] = df_diferentes31['Nova Receita Líquida']

df_diferentes31['Comissão'] = df_diferentes31['Nova Comissão']

In [277]:

# Lista de nomes para verificar na coluna 'Assessor Principal'
nomes = [
    "DIOGO GOMES RAMOS",
    "GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA",
    "JOAO PAULO ALVES SOARES",
    "KAUE DEL DUQUE DE GODOY",
    "LUCIANA FERREIRA GONCALVES ABADE",
    "ALINE DE OLIVEIRA",
    "RODRIGO MOSSIN PANSICA"
]

# Cria a condição verificando se o valor na coluna 'Assessor Principal' está na lista de nomes
condicao = df_diferentes31RF['Assessor Principal'].isin(nomes)

# Aplica a condição usando np.where e calcula os valores com base na condição
df_diferentes31RF['Nova Receita Bruta'] = np.where(condicao, df_diferentes31RF['Receita Bruta'] * 0.50, df_diferentes31RF['Receita Bruta'] * 0.3333)

df_diferentes31RF['Nova Receita Líquida'] = np.where(condicao, df_diferentes31RF['Receita Líquida'] * 0.50, df_diferentes31RF['Receita Líquida'] * 0.3333)

df_diferentes31RF['Nova Comissão'] = np.where(condicao, df_diferentes31RF['Comissão'] * 0.50, df_diferentes31RF['Comissão'] * 0.3333)

In [278]:
df_diferentes31RF['Receita Bruta'] = df_diferentes31RF['Nova Receita Bruta']

df_diferentes31RF['Receita Líquida'] = df_diferentes31RF['Nova Receita Líquida']

df_diferentes31RF['Comissão'] = df_diferentes31RF['Nova Comissão']

In [279]:
df_diferentes_ger["Assessor_Oficial"] = df_diferentes_ger["Assessor_RV"]

In [280]:
df_diferentes_gerRF["Assessor_Oficial"] = df_diferentes_gerRF["Assessor_RF"]

In [281]:
df_diferentes31["Assessor_Oficial"] = df_diferentes31["Assessor Principal"]

In [282]:
df_diferentes31RF["Assessor_Oficial"] = df_diferentes31RF["Assessor Principal"]

In [283]:
df_diferentes_final_rv = pd.concat([df_diferentes31, df_diferentes_ger], ignore_index=True)

In [284]:
df_diferentes_final_rF = pd.concat([df_diferentes31RF, df_diferentes_gerRF], ignore_index=True)

In [285]:
df_diferentes_final_rv_ofi = df_diferentes_final_rv.drop(['Assessor_RV'], axis=1)

In [286]:
df_diferentes_final_rf_ofi = df_diferentes_final_rF.drop(['Assessor_RF'], axis=1)

In [287]:
df_igual_rv = df_igual_rv.rename(columns={'Assessor_RV': 'Assessor_Oficial'})

In [288]:
df_igual_rf = df_igual_rf.rename(columns={'Assessor_RF': 'Assessor_Oficial'})

In [289]:
df_dono["Assessor_Oficial"] = df_dono["Assessor Principal"]

In [290]:
# Condição para a duplicação
condicao = (df_dono['Categoria'] == 'RENDA VARIAVEL') | (df_dono['Categoria'] == 'RENDA FIXA') | (df_dono['Categoria'] == 'OPERACOES ESTRUTURADAS')
  
# Filtrar linhas que satisfazem a condição
linhas_condicao = df_dono[condicao]

In [291]:
# Remover linhas originais que satisfazem a condição do DataFrame original
df_dono = df_dono.drop(linhas_condicao.index)

In [292]:
df_final_Oficial = pd.concat([df_dono, df_diferentes_final_rf_ofi,df_diferentes_final_rv_ofi,df_igual_rf,df_igual_rv])

In [293]:
df_final_Oficial = df_final_Oficial.drop(columns=['Nova Receita Bruta', 'Nova Receita Líquida', 'Nova Comissão'])

In [294]:
df_final_Oficial['Receita Bruta'] = df_final_Oficial['Receita Bruta'].round(2)
df_final_Oficial['Receita Líquida'] = df_final_Oficial['Receita Líquida'].round(2)
df_final_Oficial['Comissão'] = df_final_Oficial['Comissão'].round(2)

In [295]:
df_final_Oficial['Categoria'] = df_final_Oficial['Categoria'].replace({
    'RENDA VARIAVEL': 'RENDA VARIÁVEL',
    'OPERACOES ESTRUTURADAS': 'OPERAÇÕES ESTRUTURADAS',
    'AJUSTE':'AJUSTE COMISSAO',
    'RENDA FIXA EMISSÃO BTG':'RENDA FIXA',
    'ERRO OPERACIONAL':'OUTROS',
    'DESCONTO USO MÍNIMO':'OUTROS',
    'ESTORNO CORRETAGEM':'OUTROS'
})

In [296]:
df_final_Oficial

,Mês/Ano,Assessor Principal,Conta,Cliente,Categoria,Receita Bruta,Receita Líquida,Comissão,Assessor_Oficial
0,2021-01,JONAS VICENTE DA SILVA,3712262,SAULO DE SOUZA FREITAS,FUNDOS,0.00,0.00,0.00,JONAS VICENTE DA SILVA
2,2021-01,JONAS VICENTE DA SILVA,3712262,SAULO DE SOUZA FREITAS,RENDA VARIÁVEL,12.39,11.20,7.83,JONAS VICENTE DA SILVA
4,2021-01,PAULO GOMES PAIVA,4426730,JOSE CARLOS VASCONCELOS,FUNDOS,0.00,0.00,1.34,PAULO GOMES PAIVA
6,2021-01,RODRIGO SCORSSOLINE MARTINS,4288494,GABRIEL MARCHON PASSOS,RENDA VARIÁVEL,721.40,673.43,471.40,RODRIGO SCORSSOLINE MARTINS
8,2021-01,RODRIGO SCORSSOLINE MARTINS,5826904,MARCO ANTONIO BARBOSA KOVAES,FUNDOS,0.00,0.00,8.67,RODRIGO SCORSSOLINE MARTINS
...,...,...,...,...,...,...,...,...,...
1902,2024-06,VINICIUS AUGUSTO BASILIO,4311759,RAFAEL SOUZA DA CUNHA,RENDA VARIÁVEL,248.69,232.15,162.51,VINICIUS AUGUSTO BASILIO
1903,2024-06,VINICIUS AUGUSTO BASILIO,5271374,NINA ROSA DE ARAUJO OLIVIERI PEREIRA,RENDA VARIÁVEL,23261.09,21695.92,15187.14,VINICIUS AUGUSTO BASILIO
1904,2024-06,VINICIUS AUGUSTO BASILIO,5693957,VALERIA DE CARVALHO MAGALHAES MATSUO,RENDA VARIÁVEL,594.27,554.75,388.33,VINICIUS AUGUSTO BASILIO
1905,2024-06,VIVIANE APARECIDA NEVES BENEDITO,1143964,DANILO AUGUSTO BAPTISTA,RENDA VARIÁVEL,70.13,65.47,45.83,VIVIANE APARECIDA NEVES BENEDITO
1907,2024-06,VIVIANE APARECIDA NEVES BENEDITO,1274248,VILMA SILVA NEVES,RENDA VARIÁVEL,31.67,29.56,20.69,VIVIANE APARECIDA NEVES BENEDITO

In [297]:
df_final_Oficial.to_excel(r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Área de Trabalho\relatorio_distribuido_gpt.xlsx")

In [298]:
# Selecionar as colunas necessárias para a pivotagem
# df_pivot = df_final_Oficial.pivot_table(
#     index=['Mês/Ano', 'Assessor Principal', 'Assessor_Oficial','Conta','Cliente'],
#     columns='Categoria',
#     values=['Receita Bruta', 'Receita Líquida', 'Comissão'],
#     fill_value=0
# ).reset_index()

In [299]:
# df_pivot_0 = df_pivot

In [300]:
# df_pivot_0.info()

In [301]:
# # Renomear colunas para um formato mais simples
# df_pivot_0.columns = [''.join(col).strip() if isinstance(col, tuple) else col for col in df_pivot_0.columns]

In [302]:
# df_pivot_0

In [303]:
# auc["Mês/Ano"] = auc["Mês/Ano"].astype(str)
# df_pivot_0["Mês/Ano"] = df_pivot_0["Mês/Ano"].astype(str)

In [304]:
# Mesclar os dataframes 'a' e 'b' com base nas colunas "Mês/Ano" e "Conta"
# Auc_Receita = pd.merge(auc,df_pivot_0, on=["Mês/Ano", "Conta"], how="left")

In [305]:
Auc_Captacao_base['Mês/Ano'] = pd.to_datetime(Auc_Captacao_base['Mês/Ano'], format='%Y-%m').dt.to_period('M')

In [306]:
Auc_Captacao_base.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18816 entries, 0 to 18815
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mês/Ano      18816 non-null  period[M]
 1   Ano          18816 non-null  object
 2   NomeMês      18816 non-null  object
 3   Conta        18816 non-null  int64
 4   Nome         18550 non-null  object
 5   Assessor     18589 non-null  object
 6   Valor Bruto  18816 non-null  float64
 7   CAPTAÇÃO     18816 non-null  float64
dtypes: float64(2), int64(1), object(4), period[M](1)
memory usage: 1.3+ MB

In [307]:
df_final_Oficial.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30836 entries, 0 to 1907
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Mês/Ano             30836 non-null  period[M]
 1   Assessor Principal  30836 non-null  object
 2   Conta               30836 non-null  int64
 3   Cliente             30836 non-null  object
 4   Categoria           30836 non-null  object
 5   Receita Bruta       30836 non-null  float64
 6   Receita Líquida     30836 non-null  float64
 7   Comissão            30836 non-null  float64
 8   Assessor_Oficial    30836 non-null  object
dtypes: float64(3), int64(1), object(4), period[M](1)
memory usage: 2.4+ MB

In [308]:
# Pivot table para transformar a categoria em colunas separadas
pivot_df = pd.pivot_table(df_final_Oficial, 
                          index=['Mês/Ano', 'Assessor Principal', 'Conta', 'Cliente', 'Assessor_Oficial'], 
                          columns='Categoria', 
                          values=['Receita Bruta', 'Receita Líquida', 'Comissão'], 
                          aggfunc='sum').reset_index()

In [309]:
# Flatten the column multi-index
pivot_df.columns = ['_'.join(col).strip() if type(col) is tuple else col for col in pivot_df.columns]

In [310]:
# Renomear colunas para uma nomenclatura mais amigável (opcional)
pivot_df.columns = [col.replace('_', ' ').title().replace(' ', '_') for col in pivot_df.columns]

In [311]:
pivot_df

,Mês/Ano_,Assessor_Principal_,Conta_,Cliente_,Assessor_Oficial_,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,Comissão_Fundos,...,Receita_Líquida_Derivativo,Receita_Líquida_Fee_De_Plataforma,Receita_Líquida_Fundos,Receita_Líquida_Oferta_Primária,Receita_Líquida_Oferta_Pública_Rf,Receita_Líquida_Operações_Estruturadas,Receita_Líquida_Outros,Receita_Líquida_Renda_Fixa,Receita_Líquida_Renda_Variável,Receita_Líquida_Saldo_Remunerado
0,2021-01,JONAS VICENTE DA SILVA,3712262,SAULO DE SOUZA FREITAS,JONAS VICENTE DA SILVA,NaN,NaN,NaN,NaN,0.00,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,49.94,11.20,NaN
1,2021-01,JONAS VICENTE DA SILVA,4767091,JONAS VICENTE DA SILVA,JONAS VICENTE DA SILVA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.09,NaN,NaN
2,2021-01,PAULO GOMES PAIVA,4426730,JOSE CARLOS VASCONCELOS,PAULO GOMES PAIVA,NaN,NaN,NaN,NaN,1.34,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.09,NaN,NaN
3,2021-01,RODRIGO SCORSSOLINE MARTINS,4288494,GABRIEL MARCHON PASSOS,RODRIGO SCORSSOLINE MARTINS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,673.43,NaN
4,2021-01,RODRIGO SCORSSOLINE MARTINS,5248406,ROGERIO CHAVES FAVA,RODRIGO SCORSSOLINE MARTINS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.73,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18176,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,3331554,SAMUEL DAVISON CONRADO DUTRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
18177,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,3872957,ROBINSON DOS SANTOS,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
18178,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,3988983,THIAGO PAES BARRETO,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02
18179,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,4215713,VIVIANE LIMA DE PAULA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.05
18180,2024-06,WILLIAN MATTOS SATURNINI DE OLIVEIRA,4425179,GUILHERME REBUSTINI,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02

In [312]:
# Crie as colunas de somatório
pivot_df['Receita_Bruta_Total'] = pivot_df.filter(like='Receita_Bruta').sum(axis=1)
pivot_df['Receita_Líquida_Total'] = pivot_df.filter(like='Receita_Líquida').sum(axis=1)
pivot_df['Comissão_Total'] = pivot_df.filter(like='Comissão').sum(axis=1)

In [313]:
pivot_df = pivot_df.drop(columns=['Assessor_Principal_'])

In [314]:
pivot_df = pivot_df.rename(columns={'Assessor_Oficial_': 'Assessor'})

In [315]:
# Substituir valores NaN por 0
pivot_df = pivot_df.fillna(0)

In [316]:
teste_receita = pivot_df.groupby('Mês/Ano_')['Receita_Bruta_Total'].sum()

In [317]:
teste_receita

Mês/Ano_
2021-01      44883.92
2021-02      83985.42
2021-03      98895.99
2021-04     229491.26
2021-05     202476.98
2021-06     168993.55
2021-07     231218.14
2021-08     293532.79
2021-09     388168.33
2021-10     368319.24
2021-11     439688.32
2021-12     295474.70
2022-01     432486.15
2022-02     638562.06
2022-03     653356.57
2022-04     429133.19
2022-05     835282.74
2022-06     626591.52
2022-07     622146.80
2022-08     636447.05
2022-09     489773.01
2022-10     549034.82
2022-11     418213.55
2022-12     464640.16
2023-01     514388.67
2023-02     496252.44
2023-03     420619.63
2023-04     403044.97
2023-05     603764.81
2023-06     537679.32
2023-07     380212.67
2023-08     495738.59
2023-09     660082.19
2023-10     626630.80
2023-11    1220128.37
2023-12     610104.76
2024-01     802779.50
2024-02     492338.19
2024-03     471754.17
2024-04    1042618.65
2024-05    1345775.51
2024-06      78045.84
Freq: M, Name: Receita_Bruta_Total, dtype: float64

In [318]:
pivot_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18181 entries, 0 to 18180
Data columns (total 43 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mês/Ano_                                18181 non-null  period[M]
 1   Conta_                                  18181 non-null  int64
 2   Cliente_                                18181 non-null  object
 3   Assessor                                18181 non-null  object
 4   Comissão_Ajuste_Comissao                18181 non-null  float64
 5   Comissão_Criptomoeda                    18181 non-null  float64
 6   Comissão_Derivativo                     18181 non-null  float64
 7   Comissão_Fee_De_Plataforma              18181 non-null  float64
 8   Comissão_Fundos                         18181 non-null  float64
 9   Comissão_Oferta_Primária                18181 non-null  float64
 10  Comissão_Oferta_Pública_Rf              18181 non-null  float64
 11  Comissão_Operações_Estruturadas         18181 non-null  float64
 12  Comissão_Outros                         18181 non-null  float64
 13  Comissão_Renda_Fixa                     18181 non-null  float64
 14  Comissão_Renda_Variável                 18181 non-null  float64
 15  Comissão_Saldo_Remunerado               18181 non-null  float64
 16  Receita_Bruta_Ajuste_Comissao           18181 non-null  float64
 17  Receita_Bruta_Criptomoeda               18181 non-null  float64
 18  Receita_Bruta_Derivativo                18181 non-null  float64
 19  Receita_Bruta_Fee_De_Plataforma         18181 non-null  float64
 20  Receita_Bruta_Fundos                    18181 non-null  float64
 21  Receita_Bruta_Oferta_Primária           18181 non-null  float64
 22  Receita_Bruta_Oferta_Pública_Rf         18181 non-null  float64
 23  Receita_Bruta_Operações_Estruturadas    18181 non-null  float64
 24  Receita_Bruta_Outros                    18181 non-null  float64
 25  Receita_Bruta_Renda_Fixa                18181 non-null  float64
 26  Receita_Bruta_Renda_Variável            18181 non-null  float64
 27  Receita_Bruta_Saldo_Remunerado          18181 non-null  float64
 28  Receita_Líquida_Ajuste_Comissao         18181 non-null  float64
 29  Receita_Líquida_Criptomoeda             18181 non-null  float64
 30  Receita_Líquida_Derivativo              18181 non-null  float64
 31  Receita_Líquida_Fee_De_Plataforma       18181 non-null  float64
 32  Receita_Líquida_Fundos                  18181 non-null  float64
 33  Receita_Líquida_Oferta_Primária         18181 non-null  float64
 34  Receita_Líquida_Oferta_Pública_Rf       18181 non-null  float64
 35  Receita_Líquida_Operações_Estruturadas  18181 non-null  float64
 36  Receita_Líquida_Outros                  18181 non-null  float64
 37  Receita_Líquida_Renda_Fixa              18181 non-null  float64
 38  Receita_Líquida_Renda_Variável          18181 non-null  float64
 39  Receita_Líquida_Saldo_Remunerado        18181 non-null  float64
 40  Receita_Bruta_Total                     18181 non-null  float64
 41  Receita_Líquida_Total                   18181 non-null  float64
 42  Comissão_Total                          18181 non-null  float64
dtypes: float64(39), int64(1), object(2), period[M](1)
memory usage: 6.0+ MB

In [319]:
# pivot_df['Mês/Ano'] = pd.to_datetime(pivot_df['Mês/Ano'], format='%Y-%m').dt.to_period('M')

In [320]:
pivot_df

,Mês/Ano_,Conta_,Cliente_,Assessor,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,Comissão_Fundos,Comissão_Oferta_Primária,...,Receita_Líquida_Oferta_Primária,Receita_Líquida_Oferta_Pública_Rf,Receita_Líquida_Operações_Estruturadas,Receita_Líquida_Outros,Receita_Líquida_Renda_Fixa,Receita_Líquida_Renda_Variável,Receita_Líquida_Saldo_Remunerado,Receita_Bruta_Total,Receita_Líquida_Total,Comissão_Total
0,2021-01,3712262,SAULO DE SOUZA FREITAS,JONAS VICENTE DA SILVA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,49.94,11.20,0.00,64.77,61.14,32.80
1,2021-01,4767091,JONAS VICENTE DA SILVA,JONAS VICENTE DA SILVA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,1.09,0.00,0.00,1.14,1.09,0.54
2,2021-01,4426730,JOSE CARLOS VASCONCELOS,PAULO GOMES PAIVA,0.0,0.0,0.0,0.0,1.34,0.0,...,0.0,0.0,0.0,0.0,0.09,0.00,0.00,0.09,0.09,1.38
3,2021-01,4288494,GABRIEL MARCHON PASSOS,RODRIGO SCORSSOLINE MARTINS,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.00,673.43,0.00,721.40,673.43,471.40
4,2021-01,5248406,ROGERIO CHAVES FAVA,RODRIGO SCORSSOLINE MARTINS,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.73,0.00,0.00,0.76,0.73,0.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18176,2024-06,3331554,SAMUEL DAVISON CONRADO DUTRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
18177,2024-06,3872957,ROBINSON DOS SANTOS,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
18178,2024-06,3988983,THIAGO PAES BARRETO,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.00,0.00,0.02,0.02,0.02,0.02
18179,2024-06,4215713,VIVIANE LIMA DE PAULA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.00,0.00,0.05,0.05,0.05,0.05
18180,2024-06,4425179,GUILHERME REBUSTINI,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.00,0.00,0.02,0.02,0.02,0.02

In [321]:
pivot_df = pivot_df.rename(columns={'Mês/Ano_': 'Mês/Ano'})
pivot_df = pivot_df.rename(columns={'Conta_': 'Conta'})
pivot_df = pivot_df.rename(columns={'Cliente_': 'Nome'})

In [322]:
pivot_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18181 entries, 0 to 18180
Data columns (total 43 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mês/Ano                                 18181 non-null  period[M]
 1   Conta                                   18181 non-null  int64
 2   Nome                                    18181 non-null  object
 3   Assessor                                18181 non-null  object
 4   Comissão_Ajuste_Comissao                18181 non-null  float64
 5   Comissão_Criptomoeda                    18181 non-null  float64
 6   Comissão_Derivativo                     18181 non-null  float64
 7   Comissão_Fee_De_Plataforma              18181 non-null  float64
 8   Comissão_Fundos                         18181 non-null  float64
 9   Comissão_Oferta_Primária                18181 non-null  float64
 10  Comissão_Oferta_Pública_Rf              18181 non-null  float64
 11  Comissão_Operações_Estruturadas         18181 non-null  float64
 12  Comissão_Outros                         18181 non-null  float64
 13  Comissão_Renda_Fixa                     18181 non-null  float64
 14  Comissão_Renda_Variável                 18181 non-null  float64
 15  Comissão_Saldo_Remunerado               18181 non-null  float64
 16  Receita_Bruta_Ajuste_Comissao           18181 non-null  float64
 17  Receita_Bruta_Criptomoeda               18181 non-null  float64
 18  Receita_Bruta_Derivativo                18181 non-null  float64
 19  Receita_Bruta_Fee_De_Plataforma         18181 non-null  float64
 20  Receita_Bruta_Fundos                    18181 non-null  float64
 21  Receita_Bruta_Oferta_Primária           18181 non-null  float64
 22  Receita_Bruta_Oferta_Pública_Rf         18181 non-null  float64
 23  Receita_Bruta_Operações_Estruturadas    18181 non-null  float64
 24  Receita_Bruta_Outros                    18181 non-null  float64
 25  Receita_Bruta_Renda_Fixa                18181 non-null  float64
 26  Receita_Bruta_Renda_Variável            18181 non-null  float64
 27  Receita_Bruta_Saldo_Remunerado          18181 non-null  float64
 28  Receita_Líquida_Ajuste_Comissao         18181 non-null  float64
 29  Receita_Líquida_Criptomoeda             18181 non-null  float64
 30  Receita_Líquida_Derivativo              18181 non-null  float64
 31  Receita_Líquida_Fee_De_Plataforma       18181 non-null  float64
 32  Receita_Líquida_Fundos                  18181 non-null  float64
 33  Receita_Líquida_Oferta_Primária         18181 non-null  float64
 34  Receita_Líquida_Oferta_Pública_Rf       18181 non-null  float64
 35  Receita_Líquida_Operações_Estruturadas  18181 non-null  float64
 36  Receita_Líquida_Outros                  18181 non-null  float64
 37  Receita_Líquida_Renda_Fixa              18181 non-null  float64
 38  Receita_Líquida_Renda_Variável          18181 non-null  float64
 39  Receita_Líquida_Saldo_Remunerado        18181 non-null  float64
 40  Receita_Bruta_Total                     18181 non-null  float64
 41  Receita_Líquida_Total                   18181 non-null  float64
 42  Comissão_Total                          18181 non-null  float64
dtypes: float64(39), int64(1), object(2), period[M](1)
memory usage: 6.0+ MB

In [323]:
Auc_Captacao_base.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18816 entries, 0 to 18815
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mês/Ano      18816 non-null  period[M]
 1   Ano          18816 non-null  object
 2   NomeMês      18816 non-null  object
 3   Conta        18816 non-null  int64
 4   Nome         18550 non-null  object
 5   Assessor     18589 non-null  object
 6   Valor Bruto  18816 non-null  float64
 7   CAPTAÇÃO     18816 non-null  float64
dtypes: float64(2), int64(1), object(4), period[M](1)
memory usage: 1.3+ MB

In [324]:
Auc_Captacao_base_Receita = pd.concat([Auc_Captacao_base, pivot_df], ignore_index=True)

In [325]:
Auc_Captacao_base_Receita

,Mês/Ano,Ano,NomeMês,Conta,Nome,Assessor,Valor Bruto,CAPTAÇÃO,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,...,Receita_Líquida_Oferta_Primária,Receita_Líquida_Oferta_Pública_Rf,Receita_Líquida_Operações_Estruturadas,Receita_Líquida_Outros,Receita_Líquida_Renda_Fixa,Receita_Líquida_Renda_Variável,Receita_Líquida_Saldo_Remunerado,Receita_Bruta_Total,Receita_Líquida_Total,Comissão_Total
0,2022-01,2022,January,3475,ANA,ROBERTA HELENA PIGNATARI,376723.11,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01,2022,January,108375,ROSA,PAULO GOMES PAIVA,256158.33,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01,2022,January,142638,MARCO,VIVIANE APARECIDA NEVES BENEDITO,22187.00,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01,2022,January,305582,BRUNO,ROBERTA HELENA PIGNATARI,268681.13,-8800.01,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01,2022,January,365708,PAULO,SAULO DE SOUZA FREITAS,22.83,1000.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36992,2024-06,NaN,NaN,3331554,SAMUEL DAVISON CONRADO DUTRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
36993,2024-06,NaN,NaN,3872957,ROBINSON DOS SANTOS,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
36994,2024-06,NaN,NaN,3988983,THIAGO PAES BARRETO,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.02,0.02,0.02,0.02
36995,2024-06,NaN,NaN,4215713,VIVIANE LIMA DE PAULA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.05,0.05,0.05
36996,2024-06,NaN,NaN,4425179,GUILHERME REBUSTINI,WILLIAN MATTOS SATURNINI DE OLIVEIRA,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.02,0.02,0.02,0.02

In [326]:
# caminhoatend = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Projetos Power Bi\Relatórios\Atendimento.csv'

In [327]:
# atendimento = pd.read_csv(caminhoatend, sep=';')

In [328]:
# atendimento

In [329]:

# Realizar o merge com base na coluna 'Conta'
# Auc_Captacao_base_Receita_atendimento = pd.merge(Auc_Captacao_base_Receita, atendimento, on='Conta', how='left')

In [330]:
# Auc_Captacao_base_Receita_atendimento

In [331]:

# Preencher os valores NaN no DataFrame resultante com os valores correspondentes no DataFrame `atendimento`
# Auc_Captacao_base_Receita_atendimento['Assessor_Oficial_'] = Auc_Captacao_base_Receita_atendimento['Assessor_Oficial_'].combine_first(Auc_Captacao_base_Receita_atendimento['Assessor_y'])

In [332]:
# Auc_Captacao_base_Receita_atendimento

In [333]:
Auc_Captacao_base_Receita = Auc_Captacao_base_Receita.rename(columns={'Assessor_Oficial_': 'Assessor_Oficial'})
Auc_Captacao_base_Receita = Auc_Captacao_base_Receita.rename(columns={'Valor Bruto': 'Auc'})

In [334]:
Auc_Captacao_base_Receita = Auc_Captacao_base_Receita.drop(columns=['Ano', 'NomeMês'])

In [335]:
Auc_Captacao_base_Receita = Auc_Captacao_base_Receita.fillna(0)

In [336]:
Auc_Captacao_base_Receita

,Mês/Ano,Conta,Nome,Assessor,Auc,CAPTAÇÃO,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,...,Receita_Líquida_Oferta_Primária,Receita_Líquida_Oferta_Pública_Rf,Receita_Líquida_Operações_Estruturadas,Receita_Líquida_Outros,Receita_Líquida_Renda_Fixa,Receita_Líquida_Renda_Variável,Receita_Líquida_Saldo_Remunerado,Receita_Bruta_Total,Receita_Líquida_Total,Comissão_Total
0,2022-01,3475,ANA,ROBERTA HELENA PIGNATARI,376723.11,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
1,2022-01,108375,ROSA,PAULO GOMES PAIVA,256158.33,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
2,2022-01,142638,MARCO,VIVIANE APARECIDA NEVES BENEDITO,22187.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
3,2022-01,305582,BRUNO,ROBERTA HELENA PIGNATARI,268681.13,-8800.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
4,2022-01,365708,PAULO,SAULO DE SOUZA FREITAS,22.83,1000.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36992,2024-06,3331554,SAMUEL DAVISON CONRADO DUTRA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
36993,2024-06,3872957,ROBINSON DOS SANTOS,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
36994,2024-06,3988983,THIAGO PAES BARRETO,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.02,0.02,0.02,0.02
36995,2024-06,4215713,VIVIANE LIMA DE PAULA,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.05,0.05,0.05
36996,2024-06,4425179,GUILHERME REBUSTINI,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.02,0.02,0.02,0.02

In [337]:
auc_ultimo_mes = Auc_Captacao_base_Receita[Auc_Captacao_base_Receita['Mês/Ano'] == '2024-06']
auc_ultimo_mes = auc_ultimo_mes['Auc'].sum()
auc_ultimo_mes

1352881046.94

In [338]:
teste_receita2 = Auc_Captacao_base_Receita.groupby('Mês/Ano')['Receita_Bruta_Total'].sum()
teste_receita2

Mês/Ano
2021-01      44883.92
2021-02      83985.42
2021-03      98895.99
2021-04     229491.26
2021-05     202476.98
2021-06     168993.55
2021-07     231218.14
2021-08     293532.79
2021-09     388168.33
2021-10     368319.24
2021-11     439688.32
2021-12     295474.70
2022-01     432486.15
2022-02     638562.06
2022-03     653356.57
2022-04     429133.19
2022-05     835282.74
2022-06     626591.52
2022-07     622146.80
2022-08     636447.05
2022-09     489773.01
2022-10     549034.82
2022-11     418213.55
2022-12     464640.16
2023-01     514388.67
2023-02     496252.44
2023-03     420619.63
2023-04     403044.97
2023-05     603764.81
2023-06     537679.32
2023-07     380212.67
2023-08     495738.59
2023-09     660082.19
2023-10     626630.80
2023-11    1220128.37
2023-12     610104.76
2024-01     802779.50
2024-02     492338.19
2024-03     471754.17
2024-04    1042618.65
2024-05    1345775.51
2024-06      78045.84
Freq: M, Name: Receita_Bruta_Total, dtype: float64

In [339]:
# Auc_Captacao_base_Receita.to_csv(r"C:\Users\WelberOliveira\CursoRPA\Dashboard\Geral.csv")

In [340]:
Auc_Captacao_base_Receita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36997 entries, 0 to 36996
Data columns (total 45 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mês/Ano                                 36997 non-null  period[M]
 1   Conta                                   36997 non-null  int64
 2   Nome                                    36997 non-null  object
 3   Assessor                                36997 non-null  object
 4   Auc                                     36997 non-null  float64
 5   CAPTAÇÃO                                36997 non-null  float64
 6   Comissão_Ajuste_Comissao                36997 non-null  float64
 7   Comissão_Criptomoeda                    36997 non-null  float64
 8   Comissão_Derivativo                     36997 non-null  float64
 9   Comissão_Fee_De_Plataforma              36997 non-null  float64
 10  Comissão_Fundos                         36997 non-null  float64
 11  Comissão_Oferta_Primária                36997 non-null  float64
 12  Comissão_Oferta_Pública_Rf              36997 non-null  float64
 13  Comissão_Operações_Estruturadas         36997 non-null  float64
 14  Comissão_Outros                         36997 non-null  float64
 15  Comissão_Renda_Fixa                     36997 non-null  float64
 16  Comissão_Renda_Variável                 36997 non-null  float64
 17  Comissão_Saldo_Remunerado               36997 non-null  float64
 18  Receita_Bruta_Ajuste_Comissao           36997 non-null  float64
 19  Receita_Bruta_Criptomoeda               36997 non-null  float64
 20  Receita_Bruta_Derivativo                36997 non-null  float64
 21  Receita_Bruta_Fee_De_Plataforma         36997 non-null  float64
 22  Receita_Bruta_Fundos                    36997 non-null  float64
 23  Receita_Bruta_Oferta_Primária           36997 non-null  float64
 24  Receita_Bruta_Oferta_Pública_Rf         36997 non-null  float64
 25  Receita_Bruta_Operações_Estruturadas    36997 non-null  float64
 26  Receita_Bruta_Outros                    36997 non-null  float64
 27  Receita_Bruta_Renda_Fixa                36997 non-null  float64
 28  Receita_Bruta_Renda_Variável            36997 non-null  float64
 29  Receita_Bruta_Saldo_Remunerado          36997 non-null  float64
 30  Receita_Líquida_Ajuste_Comissao         36997 non-null  float64
 31  Receita_Líquida_Criptomoeda             36997 non-null  float64
 32  Receita_Líquida_Derivativo              36997 non-null  float64
 33  Receita_Líquida_Fee_De_Plataforma       36997 non-null  float64
 34  Receita_Líquida_Fundos                  36997 non-null  float64
 35  Receita_Líquida_Oferta_Primária         36997 non-null  float64
 36  Receita_Líquida_Oferta_Pública_Rf       36997 non-null  float64
 37  Receita_Líquida_Operações_Estruturadas  36997 non-null  float64
 38  Receita_Líquida_Outros                  36997 non-null  float64
 39  Receita_Líquida_Renda_Fixa              36997 non-null  float64
 40  Receita_Líquida_Renda_Variável          36997 non-null  float64
 41  Receita_Líquida_Saldo_Remunerado        36997 non-null  float64
 42  Receita_Bruta_Total                     36997 non-null  float64
 43  Receita_Líquida_Total                   36997 non-null  float64
 44  Comissão_Total                          36997 non-null  float64
dtypes: float64(41), int64(1), object(2), period[M](1)
memory usage: 12.7+ MB

In [341]:
teste_auc = Auc_Captacao_base_Receita.groupby(['Mês/Ano'])['Auc'].sum().reset_index()
teste_auc

    Mês/Ano           Auc
0   2021-01  0.000000e+00
1   2021-02  0.000000e+00
2   2021-03  0.000000e+00
3   2021-04  0.000000e+00
4   2021-05  0.000000e+00
5   2021-06  0.000000e+00
6   2021-07  0.000000e+00
7   2021-08  0.000000e+00
8   2021-09  0.000000e+00
9   2021-10  0.000000e+00
10  2021-11  0.000000e+00
11  2021-12  0.000000e+00
12  2022-01  1.481429e+08
13  2022-02  1.513128e+08
14  2022-03  1.651709e+08
15  2022-04  1.690283e+08
16  2022-05  1.788490e+08
17  2022-06  1.813503e+08
18  2022-07  1.872732e+08
19  2022-08  1.957799e+08
20  2022-09  2.021524e+08
21  2022-10  2.119581e+08
22  2022-11  2.127539e+08
23  2022-12  2.130836e+08
24  2023-01  2.179413e+08
25  2023-02  2.152587e+08
26  2023-03  2.158692e+08
27  2023-04  2.207663e+08
28  2023-05  2.252963e+08
29  2023-06  2.234636e+08
30  2023-07  2.297125e+08
31  2023-08  2.689777e+08
32  2023-09  4.833870e+08
33  2023-10  5.947198e+08
34  2023-11  9.654261e+08
35  2023-12  9.934557e+08
36  2024-01  1.289599e+09
37  2024-02  1.360341e+09
38  2024-03  1.384951e+09
39  2024-04  1.632404e+09
40  2024-05  1.632393e+09
41  2024-06  1.352881e+09

In [342]:

def formatar_numero(valor):
    try:
        # Converter para float e formatar como moeda brasileira
        valor_formatado = f"{float(valor):,.2f}"  # Usar duas casas decimais
        valor_formatado = valor_formatado.replace(",", "@").replace(".", ",").replace("@", ".")
        return "R$ " + valor_formatado
    except ValueError:
        # Retorna o valor original se a conversão falhar
        return valor

In [343]:
# # Converter as colunas a partir do índice 2 para string
# for col in Auc_Captacao_base_Receita_atendimento.columns[3:]:
#     Auc_Captacao_base_Receita_atendimento[col] = Auc_Captacao_base_Receita_atendimento[col].astype(str)

# # Aplicar a função formatar_numero
# for col in Auc_Captacao_base_Receita_atendimento.columns[3:]:
#     Auc_Captacao_base_Receita_atendimento[col] = Auc_Captacao_base_Receita_atendimento[col].apply(formatar_numero)

In [344]:
# Auc_Captacao_base_Receita_atendimento

In [345]:
# # Converter as colunas a partir do índice 2 para string
# for col in teste_auc.columns[1:]:
#     teste_auc[col] = teste_auc[col].astype(str)

# # Aplicar a função formatar_numero
# for col in teste_auc.columns[1:]:
#     teste_auc[col] = teste_auc[col].apply(formatar_numero)

In [346]:
# teste_auc

In [347]:
# df_cleaned = Auc_Captacao_base_Receita_atendimento.drop_duplicates(subset=['Mês/Ano', 'Conta'])

In [348]:
# df_cleaned

In [349]:
# df_cleaned1 = df_cleaned.groupby(['Mês/Ano'])['Auc'].sum().reset_index()
# df_cleaned1

In [350]:
# df_cleaned3 = df_cleaned.groupby(['Mês/Ano'])['Receita_Bruta_Total'].sum().reset_index()

In [351]:
# df_cleaned3[['Mês/Ano','Receita_Bruta_Total']]

In [352]:
Receitageral = Auc_Captacao_base_Receita.groupby(['Mês/Ano'])['Receita_Bruta_Total'].sum().reset_index()

In [353]:
Receitageral['Mês/Ano'] = Receitageral['Mês/Ano'].astype(str)

In [354]:
import plotly.express as px
import plotly.graph_objects as go

In [355]:
fig2 = go.Figure(go.Bar(
    x=Receitageral['Mês/Ano'],
    y=Receitageral['Receita_Bruta_Total'],
    orientation='v',
    textposition='auto',
    text=Receitageral['Receita_Bruta_Total'],
    insidetextfont=dict(family='Times', size=21)
))

fig2.show()

In [356]:
graficorec = px.line(Receitageral, y='Receita_Bruta_Total', x='Mês/Ano')

In [357]:
graficorec.show()

In [358]:
graficorec.update_layout(
                        autosize=False,
                        height=350, 
                        width=850,
                        legend_orientation = 'h',
                        legend=dict(x=-0.0, y= -0.6),
                        legend_font_size=10,
                        yaxis_title=None,
                        xaxis_title=None,
                        margin=dict(
                            l=10,
                            r=10,
                            b=10,
                            t=10,
                            pad=4
                            ),
                        xaxis=dict(
                            rangeselector=dict(
                                buttons=list([
                                    dict(count=1,
                                        label="1m",
                                        step="month",
                                        stepmode="backward"),
                                    dict(count=6,
                                        label="6m",
                                        step="month",
                                        stepmode="backward"),
                                    dict(count=1,
                                        label="YTD",
                                        step="year",
                                        stepmode="todate"),
                                    dict(count=1,
                                        label="1y",
                                        step="year",
                                        stepmode="backward"),
                                    dict(step="all")
                                ])
                            ),
                            rangeslider=dict(
                                visible=False
                            ),
                            type="date"
                        )
                )

## Corban

In [359]:
import os
import pandas as pd

# Especificando o caminho para a pasta principal
caminho_pasta_principal2023 = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\OMG - CORBAN\2023'

# Colunas desejadas para o DataFrame final
colunas_desejadas = ['Data Receita', 'Conta', 'Cliente', 'Categoria', 'Produto', 'Ativo', 'Tipo Receita', 'Receita Bruta', 'Receita Líquida', 'Comissão']
df_final2023 = pd.DataFrame(columns=colunas_desejadas)

# Iterando sobre as pastas internas da pasta principal
for pasta_interna in os.listdir(caminho_pasta_principal2023):
    caminho_pasta_interna = os.path.join(caminho_pasta_principal2023, pasta_interna)

    if os.path.isdir(caminho_pasta_interna):
        lista_arquivos = os.listdir(caminho_pasta_interna)
        arquivos_filtrados = [arquivo for arquivo in lista_arquivos if arquivo.lower().endswith('.xlsx')]

        for arquivo in arquivos_filtrados:
            caminho_arquivo = os.path.join(caminho_pasta_interna, arquivo)

            # Lendo o arquivo Excel para encontrar o índice do cabeçalho
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=None)
            primeira_linha = df_temp.dropna(how='all').index[0]  # Encontrando a primeira linha não vazia

            # Lendo novamente com o índice do cabeçalho correto
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=primeira_linha)
            
            # Se os nomes das colunas no arquivo não corresponderem exatamente às colunas_desejadas,
            # crie e aplique um mapeamento de colunas aqui. Por exemplo:
            # mapeamento_colunas = {'Data': 'Data Receita', 'ClienteNome': 'Cliente', ...}
            # df_temp.rename(columns=mapeamento_colunas, inplace=True)

            # Verificando e adicionando colunas que estão faltando para alinhar com colunas_desejadas
            for coluna in colunas_desejadas:
                if coluna not in df_temp.columns:
                    df_temp[coluna] = pd.NA  # Adiciona a coluna com valores NA (faltantes)

            # Selecionando apenas as colunas desejadas
            df_temp = df_temp[colunas_desejadas]

            # Concatenando com o DataFrame final
            df_final2023 = pd.concat([df_final2023, df_temp], ignore_index=True)

df_final2023 = df_final2023.dropna(subset=['Conta'])

In [360]:
# Especificando o caminho para a pasta principal
caminho_pasta_principal2021 = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\OMG - CORBAN\2021'

# Colunas desejadas para o DataFrame final
colunas_desejadas = ['Data Receita', 'Conta', 'Cliente', 'Categoria', 'Produto', 'Ativo', 'Tipo Receita', 'Receita Bruta', 'Receita Líquida', 'Comissão']
df_final2021 = pd.DataFrame(columns=colunas_desejadas)

# Iterando sobre as pastas internas da pasta principal
for pasta_interna in os.listdir(caminho_pasta_principal2021):
    caminho_pasta_interna = os.path.join(caminho_pasta_principal2021, pasta_interna)

    if os.path.isdir(caminho_pasta_interna):
        lista_arquivos = os.listdir(caminho_pasta_interna)
        arquivos_filtrados = [arquivo for arquivo in lista_arquivos if arquivo.lower().endswith('.xlsx')]

        for arquivo in arquivos_filtrados:
            caminho_arquivo = os.path.join(caminho_pasta_interna, arquivo)

            # Lendo o arquivo Excel para encontrar o índice do cabeçalho
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=None)
            primeira_linha = df_temp.dropna(how='all').index[0]  # Encontrando a primeira linha não vazia

            # Lendo novamente com o índice do cabeçalho correto
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=primeira_linha)
            
            # Se os nomes das colunas no arquivo não corresponderem exatamente às colunas_desejadas,
            # crie e aplique um mapeamento de colunas aqui. Por exemplo:
            # mapeamento_colunas = {'Data': 'Data Receita', 'ClienteNome': 'Cliente', ...}
            # df_temp.rename(columns=mapeamento_colunas, inplace=True)

            # Verificando e adicionando colunas que estão faltando para alinhar com colunas_desejadas
            for coluna in colunas_desejadas:
                if coluna not in df_temp.columns:
                    df_temp[coluna] = pd.NA  # Adiciona a coluna com valores NA (faltantes)

            # Selecionando apenas as colunas desejadas
            df_temp = df_temp[colunas_desejadas]

            # Concatenando com o DataFrame final
            df_final2021 = pd.concat([df_final2021, df_temp], ignore_index=True)

df_final2021 = df_final2021.dropna(subset=['Conta'])

In [361]:
# Especificando o caminho para a pasta principal
caminho_pasta_principal2022 = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\OMG - CORBAN\2022'

# Colunas desejadas para o DataFrame final
colunas_desejadas = ['Data Receita', 'Conta', 'Cliente', 'Categoria', 'Produto', 'Ativo', 'Tipo Receita', 'Receita Bruta', 'Receita Líquida', 'Comissão']
df_final2022 = pd.DataFrame(columns=colunas_desejadas)

# Iterando sobre as pastas internas da pasta principal
for pasta_interna in os.listdir(caminho_pasta_principal2022):
    caminho_pasta_interna = os.path.join(caminho_pasta_principal2022, pasta_interna)

    if os.path.isdir(caminho_pasta_interna):
        lista_arquivos = os.listdir(caminho_pasta_interna)
        arquivos_filtrados = [arquivo for arquivo in lista_arquivos if arquivo.lower().endswith('.xlsx')]

        for arquivo in arquivos_filtrados:
            caminho_arquivo = os.path.join(caminho_pasta_interna, arquivo)

            # Lendo o arquivo Excel para encontrar o índice do cabeçalho
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=None)
            primeira_linha = df_temp.dropna(how='all').index[0]  # Encontrando a primeira linha não vazia

            # Lendo novamente com o índice do cabeçalho correto
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=primeira_linha)
            
            # Se os nomes das colunas no arquivo não corresponderem exatamente às colunas_desejadas,
            # crie e aplique um mapeamento de colunas aqui. Por exemplo:
            # mapeamento_colunas = {'Data': 'Data Receita', 'ClienteNome': 'Cliente', ...}
            # df_temp.rename(columns=mapeamento_colunas, inplace=True)

            # Verificando e adicionando colunas que estão faltando para alinhar com colunas_desejadas
            for coluna in colunas_desejadas:
                if coluna not in df_temp.columns:
                    df_temp[coluna] = pd.NA  # Adiciona a coluna com valores NA (faltantes)

            # Selecionando apenas as colunas desejadas
            df_temp = df_temp[colunas_desejadas]

            # Concatenando com o DataFrame final
            df_final2022 = pd.concat([df_final2022, df_temp], ignore_index=True)

df_final2022 = df_final2022.dropna(subset=['Conta'])

In [362]:

# Especificando o caminho para a pasta principal
caminho_pasta_principal2 = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\OMG - CORBAN\2024'

# Colunas desejadas para o DataFrame final
colunas_desejadas = ['Data Receita', 'Conta', 'Cliente', 'Categoria', 'Produto', 'Ativo', 'Tipo Receita', 'Receita Bruta', 'Receita Líquida', 'Comissão']
df_final2 = pd.DataFrame(columns=colunas_desejadas)

# Iterando sobre as pastas internas da pasta principal
for pasta_interna in os.listdir(caminho_pasta_principal2):
    caminho_pasta_interna = os.path.join(caminho_pasta_principal2, pasta_interna)

    if os.path.isdir(caminho_pasta_interna):
        lista_arquivos = os.listdir(caminho_pasta_interna)
        arquivos_filtrados = [arquivo for arquivo in lista_arquivos if arquivo.lower().endswith('.xlsx')]

        for arquivo in arquivos_filtrados:
            caminho_arquivo = os.path.join(caminho_pasta_interna, arquivo)

            # Lendo o arquivo Excel para encontrar o índice do cabeçalho
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=None)
            primeira_linha = df_temp.dropna(how='all').index[0]  # Encontrando a primeira linha não vazia

            # Lendo novamente com o índice do cabeçalho correto
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Detalhe', header=primeira_linha)
            
            # Se os nomes das colunas no arquivo não corresponderem exatamente às colunas_desejadas,
            # crie e aplique um mapeamento de colunas aqui. Por exemplo:
            # mapeamento_colunas = {'Data': 'Data Receita', 'ClienteNome': 'Cliente', ...}
            # df_temp.rename(columns=mapeamento_colunas, inplace=True)

            # Verificando e adicionando colunas que estão faltando para alinhar com colunas_desejadas
            for coluna in colunas_desejadas:
                if coluna not in df_temp.columns:
                    df_temp[coluna] = pd.NA  # Adiciona a coluna com valores NA (faltantes)

            # Selecionando apenas as colunas desejadas
            df_temp = df_temp[colunas_desejadas]

            # Concatenando com o DataFrame final
            df_final2 = pd.concat([df_final2, df_temp], ignore_index=True)

df_final2 = df_final2.dropna(subset=['Conta'])

In [363]:
corban = pd.concat([df_final2, df_final2021,df_final2022, df_final2023])

In [364]:
corban = corban.dropna(subset=['Receita Bruta'])

In [365]:
corban['Data Receita'] = pd.to_datetime(corban['Data Receita'])

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '13/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/03/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/03/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/03/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/03/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/03/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/03/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/08/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/07/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/07/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/07/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/07/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/07/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/10/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '13/09/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/04/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/04/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/04/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/04/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/04/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/04/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/12/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '13/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/01/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/07/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/06/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/06/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/06/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/06/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/06/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/06/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/05/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.


In [366]:
corban['Ano'] = corban['Data Receita'].dt.strftime('%Y')

In [367]:
corban['MesNum'] = corban['Data Receita'].dt.strftime('%m')

In [368]:
corban['Mês/Ano'] = corban['Ano'] + "-" + corban['MesNum']

In [369]:
corban

,Data Receita,Conta,Cliente,Categoria,Produto,Ativo,Tipo Receita,Receita Bruta,Receita Líquida,Comissão,Ano,MesNum,Mês/Ano
0,2024-04-30,471257.0,DAYANE NUNES VIANA,FEE TRANSACIONAL,CARTAO DE CREDITO,CREDIT_CARD_B2B_BLACK,FEE,0.0128,0.0128,0.0128,2024,04,2024-04
1,2024-04-30,4588063.0,MURILO DE SOUZA CHAGAS,FEE TRANSACIONAL,CARTAO DE CREDITO,CREDIT_CARD_B2B_BLACK,FEE,5.4465,5.4465,5.4465,2024,04,2024-04
2,2024-04-30,4381766.0,THIAGO RESENDE BORGES,FEE TRANSACIONAL,CARTAO DE CREDITO,CREDIT_CARD_B2B_BLACK,FEE,5.6703,5.6703,5.6703,2024,04,2024-04
3,2024-04-30,3004587.0,HERMES GOMES DA SILVA,FEE TRANSACIONAL,CARTAO DE CREDITO,CREDIT_CARD_B2B_BLACK,FEE,0.3917,0.3917,0.3917,2024,04,2024-04
4,2024-04-29,1694522.0,ALEX HANAZAKI,CAMBIO,SPOT,SPOT,Spread,329.5,314.17825,157.089125,2024,04,2024-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1308,2023-01-09,4009158.0,CARINA DO NASCIMENTO COSTA,FEE TRANSACIONAL,CARTAO DE CREDITO,BLACK,FEE,0.4241,0.4241,0.4241,2023,01,2023-01
1309,2023-01-09,1605820.0,GUILHERME HIDEKI MAGALHAES MATSUO,FEE TRANSACIONAL,CARTAO DE CREDITO,GOLD,FEE,2.1108,2.1108,2.1108,2023,01,2023-01
1310,2023-01-09,4019900.0,LO WAI MAN,FEE TRANSACIONAL,CARTAO DE CREDITO,BLACK,FEE,0.5259,0.5259,0.5259,2023,01,2023-01
1311,2023-12-09,3959747.0,DENIS CARDOSO FIRMINO,ENCARGOS,ENCARGOS,USD,Encargos,-90.0,-90.0,-90.0,2023,12,2023-12
1312,2023-01-09,3644317.0,GABRIEL DORNELLAS PIANEZ,FEE TRANSACIONAL,CARTAO DE CREDITO,BLACK,FEE,0.5976,0.5976,0.5976,2023,01,2023-01

In [370]:


corban_ = corban.groupby(['Mês/Ano','Conta','Cliente'])['Receita Bruta'].sum().reset_index()

In [371]:
corban_

      Mês/Ano      Conta                              Cliente Receita Bruta
0     2021-01  2570814.0                  APEX DO BRASIL LTDA       12005.0
1     2021-03  2650720.0                       EDGE AUTO LTDA     4086.9023
2     2021-04  2313695.0            CRISTINA DRIUSSI PERROTTA         105.0
3     2021-04  2736824.0                     RICARDO PERROTTA         105.0
4     2021-05  1381276.0          TOBIAS ALBUQUERQUE WEGENAST        939.38
...       ...        ...                                  ...           ...
1653  2024-08  4140605.0           DERIVATIVA TECNOLOGIA LTDA    1552.53116
1654  2024-08  5095101.0  CAMISA 10 ENGENHARIA ESPORTIVA LTDA      175.3925
1655  2024-09  3729189.0                          JUN YOSHIDA         387.0
1656  2024-12  1694522.0                        ALEX HANAZAKI         576.0
1657  2024-12  5273904.0                  LUCY KAZUKO HASHIBA         150.7

[1658 rows x 4 columns]

In [372]:
corban_['Mês/Ano'] = pd.to_datetime(corban_['Mês/Ano'], format='%Y-%m')

In [373]:
corban_['Mês/Ano'] = pd.to_datetime(corban_['Mês/Ano'], format='%Y-%m').dt.to_period('M')

In [374]:
corban_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1658 entries, 0 to 1657
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Mês/Ano        1658 non-null   period[M]
 1   Conta          1658 non-null   float64
 2   Cliente        1658 non-null   object
 3   Receita Bruta  1658 non-null   object
dtypes: float64(1), object(2), period[M](1)
memory usage: 51.9+ KB

In [375]:
import pandas as pd
import numpy as np
import openpyxl

In [376]:
caminhoatend = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Projetos Power Bi\Relatórios\Atendimento.csv'

In [377]:
atendimento = pd.read_csv(caminhoatend, sep=';')

In [378]:
# Realizar o merge com base na coluna 'Conta'
corban_ = pd.merge(corban_, atendimento, on='Conta', how='left')

In [379]:
corban_

,Mês/Ano,Conta,Cliente,Receita Bruta,Assessor
0,2021-01,2570814.0,APEX DO BRASIL LTDA,12005.0,PAULO GOMES PAIVA
1,2021-03,2650720.0,EDGE AUTO LTDA,4086.9023,NaN
2,2021-04,2313695.0,CRISTINA DRIUSSI PERROTTA,105.0,NaN
3,2021-04,2736824.0,RICARDO PERROTTA,105.0,NaN
4,2021-05,1381276.0,TOBIAS ALBUQUERQUE WEGENAST,939.38,PAULO GOMES PAIVA
...,...,...,...,...,...
1653,2024-08,4140605.0,DERIVATIVA TECNOLOGIA LTDA,1552.53116,VIVIANE APARECIDA NEVES BENEDITO
1654,2024-08,5095101.0,CAMISA 10 ENGENHARIA ESPORTIVA LTDA,175.3925,JOAO PAULO ALVES SOARES
1655,2024-09,3729189.0,JUN YOSHIDA,387.0,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA
1656,2024-12,1694522.0,ALEX HANAZAKI,576.0,ROBERTA HELENA PIGNATARI
1657,2024-12,5273904.0,LUCY KAZUKO HASHIBA,150.7,ALINE DE OLIVEIRA

In [380]:
corban_ = corban_.rename(columns={'Receita Bruta':'Receita_Bruta_Corban'})

In [381]:
corban_ = corban_.rename(columns={'Cliente':'Nome'})

# Fundos

In [382]:
# Especificando o caminho para a pasta principal
caminho_pasta_principal = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\Ômega AAI\Rel Comissões 2023'

# Criando um DataFrame para armazenar os dados
df_final_fundos = pd.DataFrame()

# Iterando sobre as pastas internas da pasta principal
for pasta_interna in os.listdir(caminho_pasta_principal):
    caminho_pasta_interna = os.path.join(caminho_pasta_principal, pasta_interna)

    # Verificando se é um diretório (pasta)
    if os.path.isdir(caminho_pasta_interna):
        # Obtendo a lista de arquivos na pasta interna
        lista_arquivos = os.listdir(caminho_pasta_interna)

        # Filtrando apenas os arquivos desejados (terminam com "Splitc.xlsx")
        arquivos_filtrados = [arquivo for arquivo in lista_arquivos if arquivo.lower().endswith('splitc.xlsx')]

        # Iterando sobre os arquivos filtrados e lendo a aba "Fundos" no DataFrame
        for arquivo in arquivos_filtrados:
            caminho_arquivo = os.path.join(caminho_pasta_interna, arquivo)
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Fundos')
            df_final_fundos = pd.concat([df_final_fundos, df_temp])

In [383]:
df_final_fundos = df_final_fundos.dropna(subset=['Unnamed: 0','Unnamed: 1'])

In [384]:
df_final_fundos

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
3,Data Receita,Conta,Cliente,Nome Fundo,CNPJ Fundo,Saldo Bruto,Taxa Adm,Repasse sobre Adm,Margem Diária,Comissão Bruta Diária,Comissão Líquida DIária
4,06/04/2023,003001259,KATINA MARIA FANTINEL,RIZA LOTUS FI RF DI,36498670000127,2381.79,0.0025,0.266667,0.000003,0.006299,0.00588
5,27/04/2023,001960530,MARIA ISABEL CORREA ALBORNOZ,SUL AMERICA EXCELLENCE FIRF CP,04899128000190,3407.85,0.003,0.42,0.000005,0.017029,0.015896
6,28/04/2023,002246271,ADRIEN JESUS BAUSELLS,SUL AMERICA EXCELLENCE FIRF CP,04899128000190,26222.86,0.003,0.42,0.000005,0.131032,0.122318
7,28/04/2023,003828854,RESTAURANTE VICOLO NOSTRO LTDA.,PORTO SEGURO FI REF DI CRÉDITO,18719154000101,54276.94,0.004,0.1867,0.000003,0.160789,0.150097
...,...,...,...,...,...,...,...,...,...,...,...
5590,28/09/2023,005079199,LUCIMAR ALMEIDA DE SOUZA FREITAS,ITAU PRIVILEGE REF DI FIC FIRF,41745741000189,741.41,0.003,0.3,0.000004,0.002647,0.002471
5591,05/09/2023,001960530,MARIA ISABEL CORREA ALBORNOZ,SUL AMERICA EXCELLENCE FIRF CP,04899128000190,3562.09,0.003,0.42,0.000005,0.017799,0.016616
5592,19/09/2023,001395743,GENI RODIO RIBEIRO,OPPORTUNITY SELECTION FIC FIA,13106983000197,132111.24,0.02,0.266667,0.000021,2.788608,2.603166
5593,13/09/2023,003828854,RESTAURANTE VICOLO NOSTRO LTDA.,SKOPOS INV VANGUARDA FIM,47020423000137,1080093.4,0.01,0.133333,0.000005,5.710974,5.331194
5594,04/09/2023,003712699,SILVANA BORELLA PIRAN,SKOPOS INV CAPABLANCA FIM,45126981000156,77012.67,0.015,0.1333,0.000008,0.610451,0.569856

In [385]:
# Supondo que a primeira linha contenha o cabeçalho e o DataFrame seja df_final
df_final_fundos.columns = df_final_fundos.iloc[0]

# Removendo a primeira linha (cabeçalho antigo)
df_final_fundos = df_final_fundos[1:].reset_index(drop=True)

In [386]:
# Especificando o caminho para a pasta principal
caminho_pasta_principal2 = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\Ômega AAI'

# Criando um DataFrame para armazenar os dados
df_final2 = pd.DataFrame()

# Iterando sobre as pastas internas da pasta principal
for pasta_interna in os.listdir(caminho_pasta_principal2):
    caminho_pasta_interna = os.path.join(caminho_pasta_principal2, pasta_interna)

    # Verificando se é um diretório (pasta)
    if os.path.isdir(caminho_pasta_interna):
        # Obtendo a lista de arquivos na pasta interna
        lista_arquivos = os.listdir(caminho_pasta_interna)

        # Filtrando apenas os arquivos desejados (terminam com "Splitc.xlsx")
        arquivos_filtrados = [arquivo for arquivo in lista_arquivos if arquivo.lower().endswith('splitc.xlsx')]

        # Iterando sobre os arquivos filtrados e lendo a aba "Fundos" no DataFrame
        for arquivo in arquivos_filtrados:
            caminho_arquivo = os.path.join(caminho_pasta_interna, arquivo)
            df_temp = pd.read_excel(caminho_arquivo, sheet_name='Fundos')
            df_final2 = pd.concat([df_final2, df_temp])

In [387]:
df_final2 = df_final2.dropna(subset=['Unnamed: 0','Unnamed: 1'])

In [388]:
# Supondo que a primeira linha contenha o cabeçalho e o DataFrame seja df_final
df_final2.columns = df_final2.iloc[0]

# Removendo a primeira linha (cabeçalho antigo)
df_final2 = df_final2[1:].reset_index(drop=True)

In [389]:
fundos = pd.concat([df_final2, df_final_fundos])

In [390]:
fundos = fundos[fundos['Data Receita'] != 'Data Receita']

In [391]:
df_final_fundos

3,Data Receita,Conta,Cliente,Nome Fundo,CNPJ Fundo,Saldo Bruto,Taxa Adm,Repasse sobre Adm,Margem Diária,Comissão Bruta Diária,Comissão Líquida DIária
0,06/04/2023,003001259,KATINA MARIA FANTINEL,RIZA LOTUS FI RF DI,36498670000127,2381.79,0.0025,0.266667,0.000003,0.006299,0.00588
1,27/04/2023,001960530,MARIA ISABEL CORREA ALBORNOZ,SUL AMERICA EXCELLENCE FIRF CP,04899128000190,3407.85,0.003,0.42,0.000005,0.017029,0.015896
2,28/04/2023,002246271,ADRIEN JESUS BAUSELLS,SUL AMERICA EXCELLENCE FIRF CP,04899128000190,26222.86,0.003,0.42,0.000005,0.131032,0.122318
3,28/04/2023,003828854,RESTAURANTE VICOLO NOSTRO LTDA.,PORTO SEGURO FI REF DI CRÉDITO,18719154000101,54276.94,0.004,0.1867,0.000003,0.160789,0.150097
4,25/04/2023,003015712,AUGUSTO CALDINI NETO,BTG PACTUAL INVESTMAIS SIMPLES,37953612000109,156.34,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
71655,28/09/2023,005079199,LUCIMAR ALMEIDA DE SOUZA FREITAS,ITAU PRIVILEGE REF DI FIC FIRF,41745741000189,741.41,0.003,0.3,0.000004,0.002647,0.002471
71656,05/09/2023,001960530,MARIA ISABEL CORREA ALBORNOZ,SUL AMERICA EXCELLENCE FIRF CP,04899128000190,3562.09,0.003,0.42,0.000005,0.017799,0.016616
71657,19/09/2023,001395743,GENI RODIO RIBEIRO,OPPORTUNITY SELECTION FIC FIA,13106983000197,132111.24,0.02,0.266667,0.000021,2.788608,2.603166
71658,13/09/2023,003828854,RESTAURANTE VICOLO NOSTRO LTDA.,SKOPOS INV VANGUARDA FIM,47020423000137,1080093.4,0.01,0.133333,0.000005,5.710974,5.331194
71659,04/09/2023,003712699,SILVANA BORELLA PIRAN,SKOPOS INV CAPABLANCA FIM,45126981000156,77012.67,0.015,0.1333,0.000008,0.610451,0.569856

In [392]:
fundos['Data Receita'] = pd.to_datetime(fundos['Data Receita'])

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/04/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/02/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/01/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '13/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/05/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '13/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/03/2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '13/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '19/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '26/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '20/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/04/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '23/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '14/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '31/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '15/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '24/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '25/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '21/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '16/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '18/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '17/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '30/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '29/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '22/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '28/08/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

c:\Users\WelberOliveira\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning:

Parsing '27/12/2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.


In [393]:
fundos['Ano'] = fundos['Data Receita'].dt.strftime('%Y')

In [394]:
fundos['MesNum'] = fundos['Data Receita'].dt.strftime('%m')

In [395]:
fundos['Mês/Ano'] = fundos['Ano'] + "-" + fundos['MesNum']

In [396]:
fundos['Conta'] = fundos['Conta'].astype(int).astype(str)

In [397]:

fundos_ = fundos.groupby(['Mês/Ano','Conta','Cliente'])['Comissão Bruta Diária'].sum().reset_index()

In [398]:
fundos_ = fundos_.rename(columns={'Comissão Bruta Diária':'Comissao_Bruta_Fundos'})

In [399]:
fundos_ = fundos_.rename(columns={'Cliente':'Nome'})

In [407]:
fundos_['Conta'] = fundos_['Conta'].astype(int)

In [408]:
atendimento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1158 entries, 0 to 1157
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Conta     1158 non-null   int64
 1   Assessor  1158 non-null   object
dtypes: int64(1), object(1)
memory usage: 18.2+ KB

In [409]:
# Realizar o merge com base na coluna 'Conta'
fundos_ = pd.merge(fundos_, atendimento, on='Conta', how='left')

In [410]:
fundos_['Mês/Ano'] = pd.to_datetime(fundos_['Mês/Ano'], format='%Y-%m')

In [411]:
# fundos_['Conta'] = fundos_['Conta'].astype(int).astype(str)

In [412]:
fundos_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5481 entries, 0 to 5480
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Mês/Ano                5481 non-null   datetime64[ns]
 1   Conta                  5481 non-null   int32
 2   Nome                   5481 non-null   object
 3   Comissao_Bruta_Fundos  5481 non-null   object
 4   Assessor               5288 non-null   object
dtypes: datetime64[ns](1), int32(1), object(3)
memory usage: 235.5+ KB

In [413]:
fundos_['Conta']

0       1040971
1       1064138
2        108375
3       1107742
4       1111774
         ...
5476     656376
5477     656542
5478     736905
5479     770826
5480     987245
Name: Conta, Length: 5481, dtype: int32

In [414]:
fundos_['Mês/Ano'] = pd.to_datetime(fundos_['Mês/Ano'], format='%Y-%m').dt.to_period('M')

In [415]:
fundos_corban = pd.concat([fundos_, corban_], ignore_index=True)

In [416]:
fundos_corban

,Mês/Ano,Conta,Nome,Comissao_Bruta_Fundos,Assessor,Receita_Bruta_Corban
0,2023-01,1040971.0,GERALDO FERNANDES LOPES JUNIOR,2.583556,NAIARA MAGALHAES FERNANDES CERQUEIRA,NaN
1,2023-01,1064138.0,ANDERSON CARNEIRO DE MACEDO,3.0549,ROBERTA HELENA PIGNATARI,NaN
2,2023-01,108375.0,ROSA MARIA PAULINO,114.868881,PAULO GOMES PAIVA,NaN
3,2023-01,1107742.0,GABRIEL MORAES TEIXEIRA,0.157695,NAIARA MAGALHAES FERNANDES CERQUEIRA,NaN
4,2023-01,1111774.0,REINALDO CLAUDIO DE SOUZA,2.731115,VIVIANE APARECIDA NEVES BENEDITO,NaN
...,...,...,...,...,...,...
7134,2024-08,4140605.0,DERIVATIVA TECNOLOGIA LTDA,NaN,VIVIANE APARECIDA NEVES BENEDITO,1552.53116
7135,2024-08,5095101.0,CAMISA 10 ENGENHARIA ESPORTIVA LTDA,NaN,JOAO PAULO ALVES SOARES,175.3925
7136,2024-09,3729189.0,JUN YOSHIDA,NaN,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA,387.0
7137,2024-12,1694522.0,ALEX HANAZAKI,NaN,ROBERTA HELENA PIGNATARI,576.0
7138,2024-12,5273904.0,LUCY KAZUKO HASHIBA,NaN,ALINE DE OLIVEIRA,150.7

In [417]:
Auc_Captacao_base_Receita_fundos_corban = pd.concat([Auc_Captacao_base_Receita,fundos_corban], ignore_index=True)

In [418]:
Auc_Captacao_base_Receita_fundos_corban.fillna(0)

,Mês/Ano,Conta,Nome,Assessor,Auc,CAPTAÇÃO,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,...,Receita_Líquida_Operações_Estruturadas,Receita_Líquida_Outros,Receita_Líquida_Renda_Fixa,Receita_Líquida_Renda_Variável,Receita_Líquida_Saldo_Remunerado,Receita_Bruta_Total,Receita_Líquida_Total,Comissão_Total,Comissao_Bruta_Fundos,Receita_Bruta_Corban
0,2022-01,3475.0,ANA,ROBERTA HELENA PIGNATARI,376723.11,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
1,2022-01,108375.0,ROSA,PAULO GOMES PAIVA,256158.33,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
2,2022-01,142638.0,MARCO,VIVIANE APARECIDA NEVES BENEDITO,22187.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
3,2022-01,305582.0,BRUNO,ROBERTA HELENA PIGNATARI,268681.13,-8800.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
4,2022-01,365708.0,PAULO,SAULO DE SOUZA FREITAS,22.83,1000.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44131,2024-08,4140605.0,DERIVATIVA TECNOLOGIA LTDA,VIVIANE APARECIDA NEVES BENEDITO,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1552.53116
44132,2024-08,5095101.0,CAMISA 10 ENGENHARIA ESPORTIVA LTDA,JOAO PAULO ALVES SOARES,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,175.39250
44133,2024-09,3729189.0,JUN YOSHIDA,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,387.00000
44134,2024-12,1694522.0,ALEX HANAZAKI,ROBERTA HELENA PIGNATARI,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,576.00000
44135,2024-12,5273904.0,LUCY KAZUKO HASHIBA,ALINE DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,150.70000

# PREVIDÊNCIA

In [419]:
# Especificando o caminho para os arquivos
caminho_pasta = r'C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\Relatório Comissões\OMG - Previdência'

# Obtendo a lista de arquivos na pasta
lista_arquivos = os.listdir(caminho_pasta)

# Filtrando apenas os arquivos no intervalo desejado (de '0123' até '0124') e com extensão '.xlsx'
arquivos_filtrados = [arquivo for arquivo in lista_arquivos if '0122' <= arquivo[-9:-5] <= '1224' and arquivo.lower().endswith('.xlsx')]

In [420]:
# Criando um DataFrame para armazenar os dados
df_final = pd.DataFrame()

In [421]:
# Iterando sobre os arquivos filtrados e lendo-os no DataFrame
for arquivo in arquivos_filtrados:
    caminho_arquivo = os.path.join(caminho_pasta, arquivo)
    df_temp = pd.read_excel(caminho_arquivo)
    df_final = pd.concat([df_final, df_temp])

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

c:\Users\WelberOliveira\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning:

Workbook contains no default style, apply openpyxl's default

In [422]:
df_final = df_final[['Data da Posicao','Conta Corrente','Cliente','Fundo','Comissao Bruta','Comissao Liquida','Percentual de Comissao','Saldo Financeiro']]

In [423]:
df_final['Ano'] = df_final['Data da Posicao'].dt.strftime('%Y')
df_final['MesNum'] = df_final['Data da Posicao'].dt.strftime('%m')
df_final['MesNome'] = df_final['Data da Posicao'].dt.strftime('%b')
df_final['MesNumero'] = df_final['Data da Posicao'].dt.month

df_final['DataBr'] = df_final['Data da Posicao'].dt.strftime('%d/%m/%Y')

df_final['Mês/Ano'] = df_final['Ano'] + "-" + df_final['MesNum']

In [424]:
prev = df_final.groupby(['Mês/Ano', 'Conta Corrente', 'Cliente', 'Fundo']).agg(
    Saldo_Medio_prev=('Saldo Financeiro', 'mean'),
    Comissao_Bruta_prev=('Comissao Bruta', 'sum'),
    Comissao_Liquida_prev=('Comissao Liquida', 'sum')
).reset_index().sort_values(by=['Mês/Ano'], ascending=False).round(2)

In [425]:
prev = prev.rename(columns={'Conta Corrente': 'Conta'})

In [426]:
prev

,Mês/Ano,Conta,Cliente,Fundo,Saldo_Medio_prev,Comissao_Bruta_prev,Comissao_Liquida_prev
1223,2024-05,5535427,LUIZ EDUARDO RODRIGUES GREENHALGH,SPX LANCER PLUS PREV FIC FIM,869910.70,205.07,191.44
1146,2024-05,2845925,PEDRILIA QUARTAROLI CARLOS,SUL AMÉRICA PREV FIC DE FI RF,11909.20,2.96,2.77
1132,2024-05,2298269,JOAO CARLOS LANG DE PAULA E SILVA,OMEGA PRIVATE PREV FUNDO DE INVESTIMENTO MULTI...,4952.22,3.15,2.94
1133,2024-05,2298269,JOAO CARLOS LANG DE PAULA E SILVA,SPARTA PREVIDENCIA B FIC DE FI RF CP,58835.57,11.72,10.94
1135,2024-05,2315678,LUIZ FERNANDO COSTA E SILVA,SPARTA PREVIDENCIA B FIC DE FI RF CP,380748.19,75.85,70.80
...,...,...,...,...,...,...,...
34,2023-01,2461478,CLAUDIO LUIZ NUNES,TRIGONO 70 PREVIDENCIA FIC FIM,23374.02,11.31,10.56
33,2023-01,2461478,CLAUDIO LUIZ NUNES,SUL AMÉRICA PREV FIC DE FI RF,22416.93,5.84,5.45
32,2023-01,2409201,ANA PAULA RODRIGUES COELHO,SPARTA PREVIDENCIA B FIC DE FI RF CP,174106.48,36.33,33.92
31,2023-01,2356437,ELIZETE AFONSO DOS SANTOS,TRIGONO 70 PREVIDENCIA FIC FIM,4182.53,2.02,1.89
0,2023-01,656376,ROBERTO LUIZ CHEN,SUL AMÉRICA PREV FIC DE FI RF,37709.93,19.66,18.35

In [427]:
prev = pd.merge(prev, atendimento, on='Conta', how='left')

In [428]:
prev = prev.rename(columns={'Cliente': 'Nome'})

In [429]:
prev = prev[['Mês/Ano', 'Conta', 'Nome', 'Saldo_Medio_prev', 'Comissao_Bruta_prev', 'Assessor']]

In [430]:
prev['Mês/Ano'] = pd.to_datetime(prev['Mês/Ano'], format='%Y-%m')

In [431]:
prev

,Mês/Ano,Conta,Nome,Saldo_Medio_prev,Comissao_Bruta_prev,Assessor
0,2024-05-01,5535427,LUIZ EDUARDO RODRIGUES GREENHALGH,869910.70,205.07,ALINE DE OLIVEIRA
1,2024-05-01,2845925,PEDRILIA QUARTAROLI CARLOS,11909.20,2.96,ROBERTA HELENA PIGNATARI
2,2024-05-01,2298269,JOAO CARLOS LANG DE PAULA E SILVA,4952.22,3.15,PAULO GOMES PAIVA
3,2024-05-01,2298269,JOAO CARLOS LANG DE PAULA E SILVA,58835.57,11.72,PAULO GOMES PAIVA
4,2024-05-01,2315678,LUIZ FERNANDO COSTA E SILVA,380748.19,75.85,ROBERTA HELENA PIGNATARI
...,...,...,...,...,...,...
1219,2023-01-01,2461478,CLAUDIO LUIZ NUNES,23374.02,11.31,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA
1220,2023-01-01,2461478,CLAUDIO LUIZ NUNES,22416.93,5.84,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA
1221,2023-01-01,2409201,ANA PAULA RODRIGUES COELHO,174106.48,36.33,ROBERTA HELENA PIGNATARI
1222,2023-01-01,2356437,ELIZETE AFONSO DOS SANTOS,4182.53,2.02,NAIARA MAGALHAES FERNANDES CERQUEIRA
1223,2023-01-01,656376,ROBERTO LUIZ CHEN,37709.93,19.66,PAULO GOMES PAIVA

In [432]:
prev['Mês/Ano'] = pd.to_datetime(prev['Mês/Ano'], format='%Y-%m').dt.to_period('M')

# Agrupando todas as informações

In [433]:
Auc_Captacao_base_Receita_fundos_corban_prev = pd.concat([Auc_Captacao_base_Receita_fundos_corban, prev], ignore_index=True)

In [434]:
Auc_Captacao_base_Receita_fundos_corban_prev = Auc_Captacao_base_Receita_fundos_corban_prev.fillna(0)

In [435]:
# Ordenar o DataFrame pelo índice
Auc_Captacao_base_Receita_fundos_corban_prev = Auc_Captacao_base_Receita_fundos_corban_prev.sort_index(ascending=False)

In [436]:
Auc_Captacao_base_Receita_fundos_corban_prev

,Mês/Ano,Conta,Nome,Assessor,Auc,CAPTAÇÃO,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,...,Receita_Líquida_Renda_Fixa,Receita_Líquida_Renda_Variável,Receita_Líquida_Saldo_Remunerado,Receita_Bruta_Total,Receita_Líquida_Total,Comissão_Total,Comissao_Bruta_Fundos,Receita_Bruta_Corban,Saldo_Medio_prev,Comissao_Bruta_prev
45359,2023-01,656376.0,ROBERTO LUIZ CHEN,PAULO GOMES PAIVA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37709.93,19.66
45358,2023-01,2356437.0,ELIZETE AFONSO DOS SANTOS,NAIARA MAGALHAES FERNANDES CERQUEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4182.53,2.02
45357,2023-01,2409201.0,ANA PAULA RODRIGUES COELHO,ROBERTA HELENA PIGNATARI,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,174106.48,36.33
45356,2023-01,2461478.0,CLAUDIO LUIZ NUNES,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22416.93,5.84
45355,2023-01,2461478.0,CLAUDIO LUIZ NUNES,GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23374.02,11.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2022-01,365708.0,PAULO,SAULO DE SOUZA FREITAS,22.83,1000.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
3,2022-01,305582.0,BRUNO,ROBERTA HELENA PIGNATARI,268681.13,-8800.01,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
2,2022-01,142638.0,MARCO,VIVIANE APARECIDA NEVES BENEDITO,22187.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
1,2022-01,108375.0,ROSA,PAULO GOMES PAIVA,256158.33,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
0,2022-01,3475.0,ANA,ROBERTA HELENA PIGNATARI,376723.11,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00

In [437]:
Auc_Captacao_base_Receita_fundos_corban_prev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45360 entries, 45359 to 0
Data columns (total 49 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mês/Ano                                 45360 non-null  period[M]
 1   Conta                                   45360 non-null  float64
 2   Nome                                    45360 non-null  object
 3   Assessor                                45360 non-null  object
 4   Auc                                     45360 non-null  float64
 5   CAPTAÇÃO                                45360 non-null  float64
 6   Comissão_Ajuste_Comissao                45360 non-null  float64
 7   Comissão_Criptomoeda                    45360 non-null  float64
 8   Comissão_Derivativo                     45360 non-null  float64
 9   Comissão_Fee_De_Plataforma              45360 non-null  float64
 10  Comissão_Fundos                         45360 non-null  float64
 11  Comissão_Oferta_Primária                45360 non-null  float64
 12  Comissão_Oferta_Pública_Rf              45360 non-null  float64
 13  Comissão_Operações_Estruturadas         45360 non-null  float64
 14  Comissão_Outros                         45360 non-null  float64
 15  Comissão_Renda_Fixa                     45360 non-null  float64
 16  Comissão_Renda_Variável                 45360 non-null  float64
 17  Comissão_Saldo_Remunerado               45360 non-null  float64
 18  Receita_Bruta_Ajuste_Comissao           45360 non-null  float64
 19  Receita_Bruta_Criptomoeda               45360 non-null  float64
 20  Receita_Bruta_Derivativo                45360 non-null  float64
 21  Receita_Bruta_Fee_De_Plataforma         45360 non-null  float64
 22  Receita_Bruta_Fundos                    45360 non-null  float64
 23  Receita_Bruta_Oferta_Primária           45360 non-null  float64
 24  Receita_Bruta_Oferta_Pública_Rf         45360 non-null  float64
 25  Receita_Bruta_Operações_Estruturadas    45360 non-null  float64
 26  Receita_Bruta_Outros                    45360 non-null  float64
 27  Receita_Bruta_Renda_Fixa                45360 non-null  float64
 28  Receita_Bruta_Renda_Variável            45360 non-null  float64
 29  Receita_Bruta_Saldo_Remunerado          45360 non-null  float64
 30  Receita_Líquida_Ajuste_Comissao         45360 non-null  float64
 31  Receita_Líquida_Criptomoeda             45360 non-null  float64
 32  Receita_Líquida_Derivativo              45360 non-null  float64
 33  Receita_Líquida_Fee_De_Plataforma       45360 non-null  float64
 34  Receita_Líquida_Fundos                  45360 non-null  float64
 35  Receita_Líquida_Oferta_Primária         45360 non-null  float64
 36  Receita_Líquida_Oferta_Pública_Rf       45360 non-null  float64
 37  Receita_Líquida_Operações_Estruturadas  45360 non-null  float64
 38  Receita_Líquida_Outros                  45360 non-null  float64
 39  Receita_Líquida_Renda_Fixa              45360 non-null  float64
 40  Receita_Líquida_Renda_Variável          45360 non-null  float64
 41  Receita_Líquida_Saldo_Remunerado        45360 non-null  float64
 42  Receita_Bruta_Total                     45360 non-null  float64
 43  Receita_Líquida_Total                   45360 non-null  float64
 44  Comissão_Total                          45360 non-null  float64
 45  Comissao_Bruta_Fundos                   45360 non-null  float64
 46  Receita_Bruta_Corban                    45360 non-null  float64
 47  Saldo_Medio_prev                        45360 non-null  float64
 48  Comissao_Bruta_prev                     45360 non-null  float64
dtypes: float64(46), object(2), period[M](1)
memory usage: 17.3+ MB

In [438]:
# Verificar o tipo da coluna 'Mês/Ano'
print(Auc_Captacao_base_Receita_fundos_corban_prev['Mês/Ano'].dtype)

period[M]

In [439]:
# Converter a coluna 'Mês/Ano' para datetime
Auc_Captacao_base_Receita_fundos_corban_prev['Mês/Ano'] = Auc_Captacao_base_Receita_fundos_corban_prev["Mês/Ano"].dt.to_timestamp()

In [440]:

Auc_Captacao_base_Receita_fundos_corban_prev['Mês/Ano'] = Auc_Captacao_base_Receita_fundos_corban_prev['Mês/Ano'].dt.to_period('M')

In [443]:
Auc_Captacao_base_Receita_fundos_corban_prev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45360 entries, 18848 to 42325
Data columns (total 49 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mês/Ano                                 45360 non-null  period[M]
 1   Conta                                   45360 non-null  float64
 2   Nome                                    45360 non-null  object
 3   Assessor                                45360 non-null  object
 4   Auc                                     45360 non-null  float64
 5   CAPTAÇÃO                                45360 non-null  float64
 6   Comissão_Ajuste_Comissao                45360 non-null  float64
 7   Comissão_Criptomoeda                    45360 non-null  float64
 8   Comissão_Derivativo                     45360 non-null  float64
 9   Comissão_Fee_De_Plataforma              45360 non-null  float64
 10  Comissão_Fundos                         45360 non-null  float64
 11  Comissão_Oferta_Primária                45360 non-null  float64
 12  Comissão_Oferta_Pública_Rf              45360 non-null  float64
 13  Comissão_Operações_Estruturadas         45360 non-null  float64
 14  Comissão_Outros                         45360 non-null  float64
 15  Comissão_Renda_Fixa                     45360 non-null  float64
 16  Comissão_Renda_Variável                 45360 non-null  float64
 17  Comissão_Saldo_Remunerado               45360 non-null  float64
 18  Receita_Bruta_Ajuste_Comissao           45360 non-null  float64
 19  Receita_Bruta_Criptomoeda               45360 non-null  float64
 20  Receita_Bruta_Derivativo                45360 non-null  float64
 21  Receita_Bruta_Fee_De_Plataforma         45360 non-null  float64
 22  Receita_Bruta_Fundos                    45360 non-null  float64
 23  Receita_Bruta_Oferta_Primária           45360 non-null  float64
 24  Receita_Bruta_Oferta_Pública_Rf         45360 non-null  float64
 25  Receita_Bruta_Operações_Estruturadas    45360 non-null  float64
 26  Receita_Bruta_Outros                    45360 non-null  float64
 27  Receita_Bruta_Renda_Fixa                45360 non-null  float64
 28  Receita_Bruta_Renda_Variável            45360 non-null  float64
 29  Receita_Bruta_Saldo_Remunerado          45360 non-null  float64
 30  Receita_Líquida_Ajuste_Comissao         45360 non-null  float64
 31  Receita_Líquida_Criptomoeda             45360 non-null  float64
 32  Receita_Líquida_Derivativo              45360 non-null  float64
 33  Receita_Líquida_Fee_De_Plataforma       45360 non-null  float64
 34  Receita_Líquida_Fundos                  45360 non-null  float64
 35  Receita_Líquida_Oferta_Primária         45360 non-null  float64
 36  Receita_Líquida_Oferta_Pública_Rf       45360 non-null  float64
 37  Receita_Líquida_Operações_Estruturadas  45360 non-null  float64
 38  Receita_Líquida_Outros                  45360 non-null  float64
 39  Receita_Líquida_Renda_Fixa              45360 non-null  float64
 40  Receita_Líquida_Renda_Variável          45360 non-null  float64
 41  Receita_Líquida_Saldo_Remunerado        45360 non-null  float64
 42  Receita_Bruta_Total                     45360 non-null  float64
 43  Receita_Líquida_Total                   45360 non-null  float64
 44  Comissão_Total                          45360 non-null  float64
 45  Comissao_Bruta_Fundos                   45360 non-null  float64
 46  Receita_Bruta_Corban                    45360 non-null  float64
 47  Saldo_Medio_prev                        45360 non-null  float64
 48  Comissao_Bruta_prev                     45360 non-null  float64
dtypes: float64(46), object(2), period[M](1)
memory usage: 17.3+ MB

In [444]:
# Ordenando o DataFrame pela coluna 'Mes/Ano'
Auc_Captacao_base_Receita_fundos_corban_prev = Auc_Captacao_base_Receita_fundos_corban_prev.sort_values(by='Mês/Ano')

In [445]:
Auc_Captacao_base_Receita_fundos_corban_prev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45360 entries, 18848 to 42325
Data columns (total 49 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mês/Ano                                 45360 non-null  period[M]
 1   Conta                                   45360 non-null  float64
 2   Nome                                    45360 non-null  object
 3   Assessor                                45360 non-null  object
 4   Auc                                     45360 non-null  float64
 5   CAPTAÇÃO                                45360 non-null  float64
 6   Comissão_Ajuste_Comissao                45360 non-null  float64
 7   Comissão_Criptomoeda                    45360 non-null  float64
 8   Comissão_Derivativo                     45360 non-null  float64
 9   Comissão_Fee_De_Plataforma              45360 non-null  float64
 10  Comissão_Fundos                         45360 non-null  float64
 11  Comissão_Oferta_Primária                45360 non-null  float64
 12  Comissão_Oferta_Pública_Rf              45360 non-null  float64
 13  Comissão_Operações_Estruturadas         45360 non-null  float64
 14  Comissão_Outros                         45360 non-null  float64
 15  Comissão_Renda_Fixa                     45360 non-null  float64
 16  Comissão_Renda_Variável                 45360 non-null  float64
 17  Comissão_Saldo_Remunerado               45360 non-null  float64
 18  Receita_Bruta_Ajuste_Comissao           45360 non-null  float64
 19  Receita_Bruta_Criptomoeda               45360 non-null  float64
 20  Receita_Bruta_Derivativo                45360 non-null  float64
 21  Receita_Bruta_Fee_De_Plataforma         45360 non-null  float64
 22  Receita_Bruta_Fundos                    45360 non-null  float64
 23  Receita_Bruta_Oferta_Primária           45360 non-null  float64
 24  Receita_Bruta_Oferta_Pública_Rf         45360 non-null  float64
 25  Receita_Bruta_Operações_Estruturadas    45360 non-null  float64
 26  Receita_Bruta_Outros                    45360 non-null  float64
 27  Receita_Bruta_Renda_Fixa                45360 non-null  float64
 28  Receita_Bruta_Renda_Variável            45360 non-null  float64
 29  Receita_Bruta_Saldo_Remunerado          45360 non-null  float64
 30  Receita_Líquida_Ajuste_Comissao         45360 non-null  float64
 31  Receita_Líquida_Criptomoeda             45360 non-null  float64
 32  Receita_Líquida_Derivativo              45360 non-null  float64
 33  Receita_Líquida_Fee_De_Plataforma       45360 non-null  float64
 34  Receita_Líquida_Fundos                  45360 non-null  float64
 35  Receita_Líquida_Oferta_Primária         45360 non-null  float64
 36  Receita_Líquida_Oferta_Pública_Rf       45360 non-null  float64
 37  Receita_Líquida_Operações_Estruturadas  45360 non-null  float64
 38  Receita_Líquida_Outros                  45360 non-null  float64
 39  Receita_Líquida_Renda_Fixa              45360 non-null  float64
 40  Receita_Líquida_Renda_Variável          45360 non-null  float64
 41  Receita_Líquida_Saldo_Remunerado        45360 non-null  float64
 42  Receita_Bruta_Total                     45360 non-null  float64
 43  Receita_Líquida_Total                   45360 non-null  float64
 44  Comissão_Total                          45360 non-null  float64
 45  Comissao_Bruta_Fundos                   45360 non-null  float64
 46  Receita_Bruta_Corban                    45360 non-null  float64
 47  Saldo_Medio_prev                        45360 non-null  float64
 48  Comissao_Bruta_prev                     45360 non-null  float64
dtypes: float64(46), object(2), period[M](1)
memory usage: 17.3+ MB

In [446]:
# ============== Caminho do arquivo Captação
caminhometasgerais = r"C:\Users\WelberOliveira\OneDrive - OMEGA INVEST AGENTE AUTONOMO DE INVESTIMENTOS LTDA\MIS - Interno\Projetos Power Bi\Relatórios\Resultados_BTG.xlsx"

# ============== Criando DF para trabalhar com os dados Captação
metas = pd.read_excel(caminhometasgerais)

In [447]:
metas = metas[['Data','Receita_Meta','NNM_Meta', 'Roa_Meta','Auc_Meta']]

In [448]:
metas['Ano'] = metas['Data'].dt.strftime('%Y')
metas['MesNum'] = metas['Data'].dt.strftime('%m')
metas['Mês/Ano'] = metas['Ano'] + "-" + metas['MesNum']

In [449]:
metas['NomeMês'] = metas['Data'].dt.strftime('%B')

In [450]:
metas

,Data,Receita_Meta,NNM_Meta,Roa_Meta,Auc_Meta,Ano,MesNum,Mês/Ano,NomeMês
0,2022-01-01,476000,5000000,0.024375,118000000,2022,01,2022-01,January
1,2022-02-01,401000,5000000,0.024375,127000000,2022,02,2022-02,February
2,2022-03-01,527000,5000000,0.024375,136000000,2022,03,2022-03,March
3,2022-04-01,424000,5000000,0.024375,145000000,2022,04,2022-04,April
4,2022-05-01,533000,5000000,0.024375,154000000,2022,05,2022-05,May
5,2022-06-01,522000,5000000,0.024375,163000000,2022,06,2022-06,June
6,2022-07-01,538000,6000000,0.024375,172000000,2022,07,2022-07,July
7,2022-08-01,608000,6000000,0.024375,181000000,2022,08,2022-08,August
8,2022-09-01,545000,6000000,0.024375,190000000,2022,09,2022-09,September
9,2022-10-01,590000,6000000,0.024375,199000000,2022,10,2022-10,October
10,2022-11-01,578000,6000000,0.024375,208000000,2022,11,2022-11,November
11,2022-12-01,595000,6000000,0.024375,217000000,2022,12,2022-12,December
12,2023-01-01,479000,8000000,0.024300,226000000,2023,01,2023-01,January
13,2023-02-01,409000,8000000,0.024300,235000000,2023,02,2023-02,February
14,2023-03-01,544000,8000000,0.024400,245000000,2023,03,2023-03,March
15,2023-04-01,443000,8000000,0.024400,254000000,2023,04,2023-04,April
16,2023-05-01,562000,8000000,0.024400,264000000,2023,05,2023-05,May
17,2023-06-01,557000,8000000,0.024400,274000000,2023,06,2023-06,June
18,2023-07-01,580000,10000000,0.024300,286000000,2023,07,2023-07,July
19,2023-08-01,663000,10000000,0.024400,298000000,2023,08,2023-08,August
20,2023-09-01,601000,10000000,0.024400,310000000,2023,09,2023-09,September
21,2023-10-01,656000,10000000,0.024400,323000000,2023,10,2023-10,October
22,2023-11-01,650000,10000000,0.024400,335000000,2023,11,2023-11,November
23,2023-12-01,675000,10000000,0.024400,348000000,2023,12,2023-12,December
24,2024-01-01,949000,320000000,0.008200,1324000000,2024,01,2024-01,January
25,2024-02-01,837000,15000000,0.008200,1349000000,2024,02,2024-02,February
26,2024-03-01,900000,15000000,0.008200,1374000000,2024,03,2024-03,March
27,2024-04-01,1010000,15000000,0.008200,1399000000,2024,04,2024-04,April
28,2024-05-01,985000,15000000,0.008300,1425000000,2024,05,2024-05,May
29,2024-06-01,957000,15000000,0.008300,1450000000,2024,06,2024-06,June
30,2024-07-01,1123000,15000000,0.008300,1476000000,2024,07,2024-07,July
31,2024-08-01,1095000,15000000,0.008400,1502000000,2024,08,2024-08,August
32,2024-09-01,1066000,15000000,0.008400,1528000000,2024,09,2024-09,September
33,2024-10-01,1190000,15000000,0.008400,1554000000,2024,10,2024-10,October
34,2024-11-01,1054000,15000000,0.008800,1581000000,2024,11,2024-11,November
35,2024-12-01,1128000,15000000,0.008400,1607000000,2024,12,2024-12,December

In [451]:
metas = metas[['Mês/Ano','Receita_Meta','NNM_Meta', 'Roa_Meta','Auc_Meta']]

In [452]:
metas['Mês/Ano'] = pd.to_datetime(metas['Mês/Ano'], format='%Y-%m').dt.to_period('M')

metas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Mês/Ano       36 non-null     period[M]
 1   Receita_Meta  36 non-null     int64
 2   NNM_Meta      36 non-null     int64
 3   Roa_Meta      36 non-null     float64
 4   Auc_Meta      36 non-null     int64
dtypes: float64(1), int64(3), period[M](1)
memory usage: 1.5 KB

C:\Users\WelberOliveira\AppData\Local\Temp\ipykernel_15748\1322483412.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [453]:
metas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Mês/Ano       36 non-null     period[M]
 1   Receita_Meta  36 non-null     int64
 2   NNM_Meta      36 non-null     int64
 3   Roa_Meta      36 non-null     float64
 4   Auc_Meta      36 non-null     int64
dtypes: float64(1), int64(3), period[M](1)
memory usage: 1.5 KB

In [454]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas = pd.concat([Auc_Captacao_base_Receita_fundos_corban_prev, metas], ignore_index=True)

In [455]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas = Auc_Captacao_base_Receita_fundos_corban_prev_metas.fillna(0)

In [456]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas = Auc_Captacao_base_Receita_fundos_corban_prev_metas.sort_values(by='Mês/Ano')

In [457]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas

,Mês/Ano,Conta,Nome,Assessor,Auc,CAPTAÇÃO,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,...,Receita_Líquida_Total,Comissão_Total,Comissao_Bruta_Fundos,Receita_Bruta_Corban,Saldo_Medio_prev,Comissao_Bruta_prev,Receita_Meta,NNM_Meta,Roa_Meta,Auc_Meta
0,2021-01,4605846.0,CLEDENIR CORDIOLI JUNIOR,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.0,0.0,...,217.80,152.46,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
20,2021-01,5267836.0,MARCO ANTONIO RIBEIRO,SAULO DE SOUZA FREITAS,0.0,0.0,0.0,0.0,0.0,0.0,...,1239.98,867.99,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
21,2021-01,5248406.0,ROGERIO CHAVES FAVA,RODRIGO SCORSSOLINE MARTINS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.73,0.36,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
22,2021-01,5826904.0,MARCO ANTONIO BARBOSA KOVAES,RODRIGO SCORSSOLINE MARTINS,0.0,0.0,0.0,0.0,0.0,0.0,...,1008.27,672.63,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
23,2021-01,305582.0,BRUNO FERNANDES BERNARDES,ROBERTA HELENA PIGNATARI,0.0,0.0,0.0,0.0,0.0,0.0,...,3.63,1.82,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45237,2024-12,3779465.0,GERSONITA MENDONCA PONTES,ROBERTA HELENA PIGNATARI,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.013084,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
45238,2024-12,3823575.0,GUASTALLA PARTICIPACOES E EMPREENDIMENTOS LTDA.,PAULO GOMES PAIVA,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,138.491942,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
45239,2024-12,3699359.0,LETICIA GUZO DE OLIVEIRA,VIVIANE APARECIDA NEVES BENEDITO,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.008088,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
45241,2024-12,3891659.0,ROBERTO SAKAMOTO,PAULO GOMES PAIVA,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,1.388312,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00
45395,2024-12,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.000000,0.0,0.0,0.0,1128000.0,15000000.0,0.0084,1.607000e+09

In [458]:
codigo_assessor = pd.DataFrame(data=[   ['ROBERTA HELENA PIGNATARI','1173274','roberta.pignatari@investomega.com.br'],
                                        ['PAULO GOMES PAIVA','968301','paulo.paiva@investomega.com.br'],
                                        ['VIVIANE APARECIDA NEVES BENEDITO','1387341','viviane.neves@investomega.com.br'],
                                        ['NAIARA MAGALHAES FERNANDES CERQUEIRA','4055454','naiara.magalhaes@investomega.com.br'],
                                        ['SAULO DE SOUZA FREITAS','1046462','saulo.freitas@investomega.com.br'],
                                        ['RONALDO CARVALHO FERNANDES JUNIOR','2032889','junior.fernandes@investomega.com.br'],
                                        ['GABRIEL PEREIRA LIMA CESAR DE OLIVEIRA','3915755','gabriel.lima@investomega.com.br'],
                                        ['VINICIUS AUGUSTO BASILIO','1152546','vinicius.basilio@investomega.com.br'],
                                        ['RODRIGO SCORSSOLINE MARTINS','1171081','rodrigo.martins@investomega.com.br'],
                                        ['KAMILA MUNHOZ ADARIO','1809121'],
                                        ['CAIO AGUIAR RODRIGUES','3199336','caio.rodrigues@investomega.com.br'],
                                        ['DIOGO GOMES RAMOS','1266319','diogo.ramos@investomega.com.br'],
                                        ['RONALDO CARVALHO FERNANDES','1167060','ronaldo.fernandes@investomega.com.br'],
                                        ['JONAS VICENTE DA SILVA','1102104','jonas.vicente@investomega.com.br'],
                                        ['WILLIAN MATTOS SATURNINI DE OLIVEIRA','1102098','willian.mattos@investomega.com.br'],
                                        ['WELBER MATTOS SATURNINI DE OLIVEIRA','1187537','welber.oliveira@investomega.com.br'],
                                        ['FELIPE MIGUEL DE BRITO E ALMEIDA','5980177','felipe.miguel@investomega.com.br'],
                                        ['JOAO PAULO ALVES SOARES','8849949','jp.soares@investomega.com.br'],
                                        ['WELLINGTON DA SILVA COELHO','1176975','wellington.coelho@investomega.com.br'],
                                        ['LUCIANA FERREIRA GONCALVES ABADE','9132962', 'luciana.abade@investomega.com.br'],
                                        ['ASSESSOR DIGITAL','000000'],
                                        ['ALINE DE OLIVEIRA','15180070', 'aline.oliveira@investomega.com.br'],
                                        ['KAUE DEL DUQUE DE GODOY','8885530','kaue.godoy@investomega.com.br'],
                                        ['RODRIGO MOSSIN PANSICA','8970657', 'rodrigo.pansica@investomega.com.br']                                    

], columns=['Assessor','Senha','Email'])

In [459]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas_assessoria = pd.merge(Auc_Captacao_base_Receita_fundos_corban_prev_metas,codigo_assessor,on=["Assessor"], how="left")

In [460]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas_assessoria

,Mês/Ano,Conta,Nome,Assessor,Auc,CAPTAÇÃO,Comissão_Ajuste_Comissao,Comissão_Criptomoeda,Comissão_Derivativo,Comissão_Fee_De_Plataforma,...,Comissao_Bruta_Fundos,Receita_Bruta_Corban,Saldo_Medio_prev,Comissao_Bruta_prev,Receita_Meta,NNM_Meta,Roa_Meta,Auc_Meta,Senha,Email
0,2021-01,4605846.0,CLEDENIR CORDIOLI JUNIOR,WILLIAN MATTOS SATURNINI DE OLIVEIRA,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1102098,willian.mattos@investomega.com.br
1,2021-01,5267836.0,MARCO ANTONIO RIBEIRO,SAULO DE SOUZA FREITAS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1046462,saulo.freitas@investomega.com.br
2,2021-01,5248406.0,ROGERIO CHAVES FAVA,RODRIGO SCORSSOLINE MARTINS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1171081,rodrigo.martins@investomega.com.br
3,2021-01,5826904.0,MARCO ANTONIO BARBOSA KOVAES,RODRIGO SCORSSOLINE MARTINS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1171081,rodrigo.martins@investomega.com.br
4,2021-01,305582.0,BRUNO FERNANDES BERNARDES,ROBERTA HELENA PIGNATARI,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1173274,roberta.pignatari@investomega.com.br
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45391,2024-12,3779465.0,GERSONITA MENDONCA PONTES,ROBERTA HELENA PIGNATARI,0.0,0.0,0.0,0.0,0.0,0.0,...,0.013084,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1173274,roberta.pignatari@investomega.com.br
45392,2024-12,3823575.0,GUASTALLA PARTICIPACOES E EMPREENDIMENTOS LTDA.,PAULO GOMES PAIVA,0.0,0.0,0.0,0.0,0.0,0.0,...,138.491942,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,968301,paulo.paiva@investomega.com.br
45393,2024-12,3699359.0,LETICIA GUZO DE OLIVEIRA,VIVIANE APARECIDA NEVES BENEDITO,0.0,0.0,0.0,0.0,0.0,0.0,...,0.008088,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,1387341,viviane.neves@investomega.com.br
45394,2024-12,3891659.0,ROBERTO SAKAMOTO,PAULO GOMES PAIVA,0.0,0.0,0.0,0.0,0.0,0.0,...,1.388312,0.0,0.0,0.0,0.0,0.0,0.0000,0.000000e+00,968301,paulo.paiva@investomega.com.br
45395,2024-12,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,1128000.0,15000000.0,0.0084,1.607000e+09,NaN,NaN

In [461]:
Auc_Captacao_base_Receita_fundos_corban_prev_metas_assessoria.to_csv(r"C:\Users\WelberOliveira\CursoRPA\Dashboard\Geral.csv")

In [463]:
# Obter o mês e ano atuais no formato 'MMM/YYYY'
current_month_year = datetime.now()

NameError: name 'datetime' is not defined